#NOTE, this is sample configuration to help craft one for custom debug
# mimics jetbrains.mps.util.LogInitializer logic
#
# IMPORTANT this file is not in use unless explicitly specified using `java.util.logging.config.file`
#           or `idea.log.config.properties.file` system properties (see LogInitializer.init())
#
handlers=java.util.logging.FileHandler java.util.logging.ConsoleHandler
.level=INFO

# There's no 'millis since start', one might want to use %1$tQ to show millis from the start of epoch,
#    which might give relative distance for two events. Just beware, it's a big number.
# Another possible format piece is %2$30s to show caller class & method there instead, although in most scenarios,
#    this would render some method of j.m.l.JULogger helper class (unless your code invoked JUL classes directly)
# %4$-7s - WARNING is the longest level name, hence 7.
java.util.logging.SimpleFormatter.format=%1$tF %1$tT,%1$tL %4$-7s - %3$30.60s - %5$s%6$s%n

java.util.logging.FileHandler.level=ALL
java.util.logging.FileHandler.append=true
java.util.logging.FileHandler.pattern=mps%g.log
java.util.logging.FileHandler.limit=1048576
java.util.logging.FileHandler.count=12
java.util.logging.FileHandler.formatter=java.util.logging.SimpleFormatter

java.util.logging.ConsoleHandler.level=WARNING
java.util.logging.ConsoleHandler.formatter=java.util.logging.SimpleFormatter

## next two are just explicitly initialized ancestor categories of most (all, perhaps?)
#  loggers MPS uses itself. We do this explicitly so that once/if IDEA overrides log configuration
#  programmatically, we still get MPS logs where we expect them to be (FileHandler configuration, above)
#  Note, here we keep useParentHandlers == true default, to get a copy of MPS messages in IDEA's idea.log
#  according to its configuration in LoggingFactory code. However, if you'd like to avoid certain groups
#  of messages polluting a log file, use "<category>.useParentHandlers=false", as in example, below
jetbrains.mps.level=INFO
jetbrains.mps.handlers=java.util.logging.FileHandler
org.jetbrains.mps.level=INFO
org.jetbrains.mps.handlers=java.util.logging.FileHandler

#these are from log.xml
#unfortunately, it's not possible to redirect certain loggers into separate files with bare JUL
jetbrains.mps.vcs.level=INFO
jetbrains.mps.vcs.useParentHandlers=false
jetbrains.mps.vcs.handlers=java.util.logging.FileHandler
com.intellij.openapi.vcs.level=INFO
com.intellij.openapi.vcs.useParentHandlers=false
com.intellij.openapi.vcs.handlers=java.util.logging.FileHandler
