package jetbrains.mps.baseLanguage.blTypes.structure;

/*Generated by MPS */

import jetbrains.mps.annotations.ResourceModule;
import jetbrains.mps.smodel.runtime.IconResource;

@ResourceModule("ed6d7656-532c-4bc2-81d1-af945aeb8280(jetbrains.mps.baseLanguage.blTypes)")
public class IconContainer {
  protected static IconResource RESOURCE_0 = new IconResource("/icons/primitive.png", "/icons/primitive_newui.svg", IconContainer.class);
}
