package jetbrains.mps.vcs.changesmanager.tree.features;

/*Generated by MPS */

import jetbrains.mps.annotations.GeneratedClass;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.mps.openapi.model.SNodeReference;
import org.jetbrains.mps.openapi.module.SRepository;

@GeneratedClass(node = "r:eed7a462-d012-4d9f-b223-97987e5d1cb3(jetbrains.mps.vcs.changesmanager.tree.features)/5060092229902868472", model = "r:eed7a462-d012-4d9f-b223-97987e5d1cb3(jetbrains.mps.vcs.changesmanager.tree.features)")
public abstract class NodeAggregationFeature extends AbstractNodeFeature {
  protected NodeAggregationFeature(@NotNull SNodeReference nodePointer) {
    super(nodePointer);
  }
  @NotNull
  @Override
  protected Feature getParent(SRepository repo) {
    return new NodeFeature(getNodePointer());
  }
}
