package jetbrains.mps.lang.dataFlow.framework.instructions;

/*Generated by MPS */


public class LabelNopInstruction extends NopInstruction {
  private String label = "unknown";

  public LabelNopInstruction(String label) {
    this.label = label;
  }

  @Override
  public String commandPresentation() {
    return label;
  }
}
