package jetbrains.mps.lang.pattern.generator.baseLanguage.template.main;

/*Generated by MPS */

import jetbrains.mps.generator.runtime.Generated;
import jetbrains.mps.generator.impl.query.QueryProviderBase;
import jetbrains.mps.generator.template.DropAttributeRuleContext;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;
import jetbrains.mps.generator.template.BaseMappingRuleContext;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import jetbrains.mps.internal.collections.runtime.IWhereFilter;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SEnumOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import jetbrains.mps.lang.quotation.behavior.NodeBuilderInitLink__BehaviorDescriptor;
import jetbrains.mps.lang.quotation.behavior.NodeBuilderInitProperty__BehaviorDescriptor;
import jetbrains.mps.generator.template.PropertyMacroContext;
import jetbrains.mps.lang.pattern.behavior.PatternVarsUtil;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.util.NameUtil;
import jetbrains.mps.generator.template.ReferenceMacroContext;
import jetbrains.mps.internal.collections.runtime.ISelector;
import jetbrains.mps.lang.pattern.behavior.AbstractPatternProvider__BehaviorDescriptor;
import jetbrains.mps.lang.pattern.behavior.PatternVariableProperty__BehaviorDescriptor;
import jetbrains.mps.smodel.SNodePointer;
import jetbrains.mps.generator.template.IfMacroContext;
import jetbrains.mps.internal.collections.runtime.Sequence;
import jetbrains.mps.lang.pattern.behavior.PatternSwitchCase__BehaviorDescriptor;
import jetbrains.mps.generator.template.SourceSubstituteMacroNodeContext;
import jetbrains.mps.typechecking.TypecheckingFacade;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SConceptOperations;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import jetbrains.mps.lang.smodel.behavior.ContainmentLinkId__BehaviorDescriptor;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SModelOperations;
import jetbrains.mps.lang.smodel.behavior.PropertyId__BehaviorDescriptor;
import jetbrains.mps.lang.core.behavior.PropertyAttribute__BehaviorDescriptor;
import jetbrains.mps.lang.smodel.behavior.ReferenceLinkId__BehaviorDescriptor;
import jetbrains.mps.lang.core.behavior.LinkAttribute__BehaviorDescriptor;
import java.util.List;
import jetbrains.mps.lang.structure.behavior.LinkDeclaration__BehaviorDescriptor;
import jetbrains.mps.generator.template.TemplateArgumentContext;
import java.util.Optional;
import jetbrains.mps.generator.template.SourceSubstituteMacroNodesContext;
import jetbrains.mps.lang.pattern.behavior.PatternBuilder__BehaviorDescriptor;
import jetbrains.mps.lang.quotation.behavior.NodeBuilderNode__BehaviorDescriptor;
import jetbrains.mps.generator.template.TemplateVarContext;
import java.util.Map;
import jetbrains.mps.generator.impl.query.ReductionRuleCondition;
import java.util.HashMap;
import org.jetbrains.annotations.NotNull;
import jetbrains.mps.generator.impl.query.QueryKey;
import jetbrains.mps.generator.template.ReductionRuleQueryContext;
import jetbrains.mps.generator.impl.GenerationFailureException;
import jetbrains.mps.generator.impl.query.MapRootRuleCondition;
import jetbrains.mps.generator.template.MapRootRuleContext;
import jetbrains.mps.generator.impl.query.DropAttributeRuleCondition;
import jetbrains.mps.generator.impl.query.SourceNodeQuery;
import jetbrains.mps.generator.impl.query.QueryKeyImpl;
import org.jetbrains.annotations.Nullable;
import jetbrains.mps.generator.impl.query.SourceNodesQuery;
import java.util.Collection;
import jetbrains.mps.util.IterableUtil;
import jetbrains.mps.generator.impl.query.PropertyValueQuery;
import org.jetbrains.mps.openapi.language.SProperty;
import jetbrains.mps.generator.impl.query.IfMacroCondition;
import jetbrains.mps.generator.impl.query.ReferenceTargetQuery;
import jetbrains.mps.generator.impl.query.VariableValueQuery;
import jetbrains.mps.generator.impl.query.CallArgumentQuery;
import org.jetbrains.mps.openapi.language.SConcept;
import org.jetbrains.mps.openapi.language.SInterfaceConcept;
import org.jetbrains.mps.openapi.language.SContainmentLink;
import org.jetbrains.mps.openapi.language.SReferenceLink;

@Generated
public class QueriesGenerated extends QueryProviderBase {
  public QueriesGenerated() {
    super(1);
  }
  public static boolean dropAttr_Condition_0_0(final DropAttributeRuleContext _context) {
    return SNodeOperations.getNodeAncestor(_context.getNode(), CONCEPTS.Quotation$UL, false, false) != null;
  }
  public static boolean dropAttr_Condition_0_1(final DropAttributeRuleContext _context) {
    return SNodeOperations.getNodeAncestor(_context.getNode(), CONCEPTS.Quotation$UL, false, false) != null;
  }
  public static boolean dropAttr_Condition_0_2(final DropAttributeRuleContext _context) {
    return SNodeOperations.getNodeAncestor(_context.getNode(), CONCEPTS.Quotation$UL, false, false) != null;
  }
  public static boolean dropAttr_Condition_0_3(final DropAttributeRuleContext _context) {
    return SNodeOperations.getNodeAncestor(_context.getNode(), CONCEPTS.Quotation$UL, false, false) != null;
  }
  public static boolean dropAttr_Condition_0_4(final DropAttributeRuleContext _context) {
    return SNodeOperations.getNodeAncestor(_context.getNode(), CONCEPTS.Quotation$UL, false, false) != null;
  }
  public static boolean rule_Condition_0_0(final BaseMappingRuleContext _context) {
    // hence inheritors == false not to handle OrPatternClause which is 
    // handled inside the template for top-most PatternExpression 
    // If there are reasonable subconcepts, might need to check 
    // !node.isInstanceOf(OrPatternClause) instead 
    // 
    return true;
  }
  public static boolean rule_Condition_0_1(final BaseMappingRuleContext _context) {
    return !(SNodeOperations.isAttribute(_context.getNode())) && SNodeOperations.getNodeAncestor(_context.getNode(), CONCEPTS.Quotation$UL, false, false) != null;
  }
  public static boolean rule_Condition_0_2(final BaseMappingRuleContext _context) {
    return ListSequence.fromList(SLinkOperations.getChildren(_context.getNode(), LINKS.case$nt1N)).all(new IWhereFilter<SNode>() {
      public boolean accept(SNode it) {
        return SNodeOperations.isInstanceOf(it, CONCEPTS.PatternSwitchCase$Mi);
      }
    });
  }
  public static boolean rule_Condition_0_3(final BaseMappingRuleContext _context) {
    return SNodeOperations.isInstanceOf(SLinkOperations.getTarget(_context.getNode(), LINKS.declaration$GelY), CONCEPTS.PatternVariableProperty$JI);
  }
  public static boolean rule_Condition_0_4(final BaseMappingRuleContext _context) {
    return SNodeOperations.isInstanceOf(SLinkOperations.getTarget(_context.getNode(), LINKS.declaration$GelY), CONCEPTS.PatternVariableNode$dP) && SNodeOperations.hasRole(SLinkOperations.getTarget(_context.getNode(), LINKS.declaration$GelY), LINKS.initValue$UJfh) && SEnumOperations.isMember(SPropertyOperations.getEnum(SLinkOperations.getTarget(SNodeOperations.cast(SNodeOperations.getParent(SLinkOperations.getTarget(_context.getNode(), LINKS.declaration$GelY)), CONCEPTS.NodeBuilderInitLink$Xj), LINKS.link$ckAZ), PROPS.metaClass$tHD7), 0xfc6f4e95b9L);
  }
  public static boolean rule_Condition_0_5(final BaseMappingRuleContext _context) {
    return SNodeOperations.isInstanceOf(SLinkOperations.getTarget(_context.getNode(), LINKS.declaration$GelY), CONCEPTS.PatternVariableNode$dP) && SNodeOperations.hasRole(SLinkOperations.getTarget(_context.getNode(), LINKS.declaration$GelY), LINKS.initValue$UJfh) && SEnumOperations.isMember(SPropertyOperations.getEnum(SLinkOperations.getTarget(SNodeOperations.cast(SNodeOperations.getParent(SLinkOperations.getTarget(_context.getNode(), LINKS.declaration$GelY)), CONCEPTS.NodeBuilderInitLink$Xj), LINKS.link$ckAZ), PROPS.metaClass$tHD7), 0xfc6f4e95b8L);
  }
  public static boolean rule_Condition_8_0(final BaseMappingRuleContext _context) {
    // under OrPattern, OrPatternVariableReference are reduced to capture() 
    return !(SNodeOperations.isInstanceOf(SNodeOperations.getParent(_context.getNode()), CONCEPTS.OrPattern$zL));
  }
  public static boolean rule_Condition_12_0(final BaseMappingRuleContext _context) {
    return (SNodeOperations.getNodeAncestor(_context.getNode(), CONCEPTS.PatternBuilder$Pa, false, false) != null);
  }
  public static boolean rule_Condition_14_0(final BaseMappingRuleContext _context) {
    return SEnumOperations.isMember(SPropertyOperations.getEnum(SLinkOperations.getTarget(_context.getNode(), LINKS.link$ckAZ), PROPS.metaClass$tHD7), 0xfc6f4e95b9L) && SNodeOperations.isInstanceOf(NodeBuilderInitLink__BehaviorDescriptor.getInitValue_id1o$2SUuvJqx.invoke(_context.getNode()), CONCEPTS.PatternVariableNode$dP);
  }
  public static boolean rule_Condition_14_1(final BaseMappingRuleContext _context) {
    return SNodeOperations.isInstanceOf(NodeBuilderInitProperty__BehaviorDescriptor.getInitValue_id1o$2SUuvKUZ.invoke(_context.getNode()), CONCEPTS.PatternVariableProperty$JI);
  }
  public static boolean rule_Condition_14_2(final BaseMappingRuleContext _context) {
    return SEnumOperations.isMember(SPropertyOperations.getEnum(SLinkOperations.getTarget(_context.getNode(), LINKS.link$ckAZ), PROPS.metaClass$tHD7), 0xfc6f4e95b8L) && SNodeOperations.isInstanceOf(NodeBuilderInitLink__BehaviorDescriptor.getInitValue_id1o$2SUuvJqx.invoke(_context.getNode()), CONCEPTS.PatternVariableNode$dP);
  }
  public static Object propertyMacro_GetValue_5_0(final PropertyMacroContext _context) {
    return PatternVarsUtil.getFieldName(SLinkOperations.getTarget(_context.getNode(), LINKS.variable$w5gw));
  }
  public static Object propertyMacro_GetValue_6_0(final PropertyMacroContext _context) {
    // there's only one dubious use of hasAntiquotations() method, in TS, where 
    // it refuses to coerce types matched against patterns with antiquotations. Nobody knows why. 
    return ListSequence.fromList(SNodeOperations.getNodeDescendants(SLinkOperations.getTarget(SLinkOperations.getTarget(_context.getNode(), LINKS.pattern$fJGl), LINKS.quotedNode$kInw), CONCEPTS.AbstractAntiquotation$Tk, false, new SAbstractConcept[]{})).isNotEmpty();
  }
  public static Object propertyMacro_GetValue_6_1(final PropertyMacroContext _context) {
    return _context.getTemplateValue() + ((Integer) _context.getVariable("cv:c"));
  }
  public static Object propertyMacro_GetValue_6_2(final PropertyMacroContext _context) {
    return _context.getTemplateValue() + ((Integer) _context.getVariable("cv:x"));
  }
  public static Object propertyMacro_GetValue_6_3(final PropertyMacroContext _context) {
    return _context.createUniqueName("Pattern_", SNodeOperations.getContainingRoot(_context.getNode()));
  }
  public static Object propertyMacro_GetValue_7_0(final PropertyMacroContext _context) {
    return SNodeOperations.getIndexInParent(_context.getNode());
  }
  public static Object propertyMacro_GetValue_8_0(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), PROPS.varName$DO_b);
  }
  public static Object propertyMacro_GetValue_8_1(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), PROPS.varName$DOAw);
  }
  public static Object propertyMacro_GetValue_8_2(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), PROPS.varName$Oh7T);
  }
  public static Object propertyMacro_GetValue_8_3(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), PROPS.varName$DO_b);
  }
  public static Object propertyMacro_GetValue_8_4(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(SLinkOperations.getTarget(_context.getNode(), LINKS.declaration$qXxw), PROPS.varName$DO_b);
  }
  public static Object propertyMacro_GetValue_13_0(final PropertyMacroContext _context) {
    return "my" + NameUtil.capitalize(SPropertyOperations.getString(_context.getNode(), PROPS.name$tAp1));
  }
  public static Object propertyMacro_GetValue_13_1(final PropertyMacroContext _context) {
    return "my" + NameUtil.capitalize(SPropertyOperations.getString(_context.getNode(), PROPS.name$tAp1));
  }
  public static Object propertyMacro_GetValue_13_2(final PropertyMacroContext _context) {
    return "myNode" + ((Integer) _context.getVariable("cv:c"));
  }
  public static Object propertyMacro_GetValue_13_3(final PropertyMacroContext _context) {
    return "p" + ((Integer) _context.getVariable("cv:c"));
  }
  public static Object propertyMacro_GetValue_13_4(final PropertyMacroContext _context) {
    return "node" + ((Integer) _context.getVariable("cv:c"));
  }
  public static Object propertyMacro_GetValue_13_5(final PropertyMacroContext _context) {
    return "p" + ((Integer) _context.getVariable("cv:c"));
  }
  public static Object propertyMacro_GetValue_13_6(final PropertyMacroContext _context) {
    return "get" + NameUtil.capitalize(SPropertyOperations.getString(_context.getNode(), PROPS.name$tAp1));
  }
  public static Object propertyMacro_GetValue_13_7(final PropertyMacroContext _context) {
    return "get" + NameUtil.capitalize(SPropertyOperations.getString(_context.getNode(), PROPS.name$tAp1));
  }
  public static Object propertyMacro_GetValue_13_8(final PropertyMacroContext _context) {
    return ((String) _context.getVariable("name"));
  }
  public static Object propertyMacro_GetValue_16_0(final PropertyMacroContext _context) {
    return _context.createIndexedName("nodeToMatch", SNodeOperations.getNodeAncestor(_context.getNode(), CONCEPTS.IMethodLike$kl, false, false), true);
  }
  public static Object propertyMacro_GetValue_16_1(final PropertyMacroContext _context) {
    return _context.createIndexedName("pattern", SNodeOperations.getNodeAncestor(_context.getNode(), CONCEPTS.IMethodLike$kl, false, false), false);
  }
  public static Object referenceMacro_GetReferent_0_0(final ReferenceMacroContext _context) {
    return _context.getOutputNodeByInputNodeAndMappingLabel(ListSequence.fromList(SNodeOperations.getNodeAncestors(_context.getNode(), CONCEPTS.PatternSwitchCase$Mi, false)).select(new ISelector<SNode, SNode>() {
      public SNode select(SNode it) {
        return SLinkOperations.getTarget(it, LINKS.pattern$LFiH);
      }
    }).where(new IWhereFilter<SNode>() {
      public boolean accept(SNode it) {
        return ListSequence.fromList(AbstractPatternProvider__BehaviorDescriptor.getVariables_id2r4rhgaEVoa.invoke(it)).contains(SLinkOperations.getTarget(_context.getNode(), LINKS.declaration$GelY));
      }
    }).first(), "patternCaseVariable");
  }
  public static Object referenceMacro_GetReferent_0_1(final ReferenceMacroContext _context) {
    return _context.getOutputNodeByInputNodeAndMappingLabel(SLinkOperations.getTarget(_context.getNode(), LINKS.declaration$GelY), "patternVarMethL");
  }
  public static Object referenceMacro_GetReferent_0_2(final ReferenceMacroContext _context) {
    return (SNode) PatternVariableProperty__BehaviorDescriptor.getDatatype_id5sDn0OnaQOz.invoke(SNodeOperations.cast(SLinkOperations.getTarget(_context.getNode(), LINKS.declaration$GelY), CONCEPTS.PatternVariableProperty$JI));
  }
  public static Object referenceMacro_GetReferent_0_3(final ReferenceMacroContext _context) {
    return _context.getOutputNodeByInputNodeAndMappingLabel(ListSequence.fromList(SNodeOperations.getNodeAncestors(_context.getNode(), CONCEPTS.PatternSwitchCase$Mi, false)).select(new ISelector<SNode, SNode>() {
      public SNode select(SNode it) {
        return SLinkOperations.getTarget(it, LINKS.pattern$LFiH);
      }
    }).where(new IWhereFilter<SNode>() {
      public boolean accept(SNode it) {
        return ListSequence.fromList(AbstractPatternProvider__BehaviorDescriptor.getVariables_id2r4rhgaEVoa.invoke(it)).contains(SLinkOperations.getTarget(_context.getNode(), LINKS.declaration$GelY));
      }
    }).first(), "patternCaseVariable");
  }
  public static Object referenceMacro_GetReferent_0_4(final ReferenceMacroContext _context) {
    return _context.getOutputNodeByInputNodeAndMappingLabel(SLinkOperations.getTarget(_context.getNode(), LINKS.declaration$GelY), "patternVarMethL");
  }
  public static Object referenceMacro_GetReferent_0_5(final ReferenceMacroContext _context) {
    return _context.getOutputNodeByInputNodeAndMappingLabel(ListSequence.fromList(SNodeOperations.getNodeAncestors(_context.getNode(), CONCEPTS.PatternSwitchCase$Mi, false)).select(new ISelector<SNode, SNode>() {
      public SNode select(SNode it) {
        return SLinkOperations.getTarget(it, LINKS.pattern$LFiH);
      }
    }).where(new IWhereFilter<SNode>() {
      public boolean accept(SNode it) {
        return ListSequence.fromList(AbstractPatternProvider__BehaviorDescriptor.getVariables_id2r4rhgaEVoa.invoke(it)).contains(SLinkOperations.getTarget(_context.getNode(), LINKS.declaration$GelY));
      }
    }).first(), "patternCaseVariable");
  }
  public static Object referenceMacro_GetReferent_0_6(final ReferenceMacroContext _context) {
    return _context.getOutputNodeByInputNodeAndMappingLabel(SLinkOperations.getTarget(_context.getNode(), LINKS.declaration$GelY), "patternVarMethL");
  }
  public static Object referenceMacro_GetReferent_7_0(final ReferenceMacroContext _context) {
    return _context.getOutputNodeByInputNodeAndMappingLabel(SNodeOperations.as(SNodeOperations.getParent(SNodeOperations.getParent(_context.getNode())), CONCEPTS.OrPatternClause$W4), "disjunctToMatcher");
  }
  public static Object referenceMacro_GetReferent_8_0(final ReferenceMacroContext _context) {
    if (SPropertyOperations.getBoolean(_context.getNode(), PROPS.stringValueMigrated$gFe8)) {
      return new SNodePointer("6ed54515-acc8-4d1e-a16c-9fd6cfe951ea/java:jetbrains.mps.lang.pattern(MPS.Core/)", "~NodeMatcher.propertyValue(org.jetbrains.mps.openapi.language.SProperty,java.lang.String)");
    } else {
      return new SNodePointer("6ed54515-acc8-4d1e-a16c-9fd6cfe951ea/java:jetbrains.mps.lang.pattern(MPS.Core/)", "~NodeMatcher.property(org.jetbrains.mps.openapi.language.SProperty,java.lang.String)");
    }
  }
  public static Object referenceMacro_GetReferent_9_0(final ReferenceMacroContext _context) {
    return _context.getOutputNodeByInputNodeAndMappingLabel(_context.getNode(), "disjunctToPatternNode");
  }
  public static Object referenceMacro_GetReferent_9_1(final ReferenceMacroContext _context) {
    return _context.getOutputNodeByInputNodeAndMappingLabel(_context.getNode(), "disjunctToMatcher");
  }
  public static Object referenceMacro_GetReferent_13_0(final ReferenceMacroContext _context) {
    return _context.getOutputNodeByInputNodeAndMappingLabel(_context.getNode(), "patternNodeVarL");
  }
  public static Object referenceMacro_GetReferent_13_1(final ReferenceMacroContext _context) {
    return _context.getOutputNodeByInputNodeAndMappingLabel(_context.getNode(), "patternPropVarL");
  }
  public static Object referenceMacro_GetReferent_14_0(final ReferenceMacroContext _context) {
    return _context.getOutputNodeByInputNodeAndMappingLabel(((SNode) _context.getVariable("nodeBuilderNode")), "nodeVariableL");
  }
  public static Object referenceMacro_GetReferent_14_1(final ReferenceMacroContext _context) {
    return _context.getOutputNodeByInputNodeAndMappingLabel(SNodeOperations.cast(NodeBuilderInitLink__BehaviorDescriptor.getInitValue_id1o$2SUuvJqx.invoke(_context.getNode()), CONCEPTS.PatternVariableNode$dP), "patternNodeVarL");
  }
  public static Object referenceMacro_GetReferent_14_2(final ReferenceMacroContext _context) {
    return _context.getOutputNodeByInputNodeAndMappingLabel(((SNode) _context.getVariable("nodeBuilderNode")), "nodeVariableL");
  }
  public static Object referenceMacro_GetReferent_14_3(final ReferenceMacroContext _context) {
    return _context.getOutputNodeByInputNodeAndMappingLabel(SNodeOperations.cast(NodeBuilderInitProperty__BehaviorDescriptor.getInitValue_id1o$2SUuvKUZ.invoke(_context.getNode()), CONCEPTS.PatternVariableProperty$JI), "patternPropVarL");
  }
  public static Object referenceMacro_GetReferent_14_4(final ReferenceMacroContext _context) {
    return _context.getOutputNodeByInputNodeAndMappingLabel(((SNode) _context.getVariable("nodeBuilderNode")), "nodeVariableL");
  }
  public static Object referenceMacro_GetReferent_14_5(final ReferenceMacroContext _context) {
    return _context.getOutputNodeByInputNodeAndMappingLabel(SNodeOperations.cast(NodeBuilderInitLink__BehaviorDescriptor.getInitValue_id1o$2SUuvJqx.invoke(_context.getNode()), CONCEPTS.PatternVariableNode$dP), "patternNodeVarL");
  }
  public static Object referenceMacro_GetReferent_15_0(final ReferenceMacroContext _context) {
    return _context.getOutputNodeByInputNodeAndMappingLabel(_context.getNode(), "patternNodeVarL");
  }
  public static Object referenceMacro_GetReferent_16_0(final ReferenceMacroContext _context) {
    return _context.getOutputNodeByInputNodeAndMappingLabel(SLinkOperations.getTarget(_context.getNode(), LINKS.pattern$LFiH), "patternCaseVariable");
  }
  public static Object referenceMacro_GetReferent_16_1(final ReferenceMacroContext _context) {
    return _context.getOutputNodeByInputNodeAndMappingLabel(SLinkOperations.getTarget(_context.getNode(), LINKS.pattern$LFiH), "patternCaseVariable");
  }
  public static Object referenceMacro_GetReferent_17_0(final ReferenceMacroContext _context) {
    return _context.getOutputNodeByInputNodeAndMappingLabel(SLinkOperations.getTarget(SLinkOperations.getTarget(_context.getNode(), LINKS.declaration$6hl0), LINKS.pattern$m3eu), "patternConstructorL");
  }
  public static Object referenceMacro_GetReferent_17_1(final ReferenceMacroContext _context) {
    return _context.getOutputNodeByInputNodeAndMappingLabel(SLinkOperations.getTarget(_context.getNode(), LINKS.pattern$65eZ), "patternConstructorL");
  }
  public static Object referenceMacro_GetReferent_18_0(final ReferenceMacroContext _context) {
    return _context.getOutputNodeByInputNodeAndMappingLabel(SLinkOperations.getTarget(SLinkOperations.getTarget(_context.getNode(), LINKS.declaration$6hl0), LINKS.pattern$m3eu), "patternClassL");
  }
  public static Object referenceMacro_GetReferent_18_1(final ReferenceMacroContext _context) {
    return _context.getOutputNodeByInputNodeAndMappingLabel(SLinkOperations.getTarget(_context.getNode(), LINKS.pattern$65eZ), "patternClassL");
  }
  public static boolean ifMacro_Condition_6_0(final IfMacroContext _context) {
    return ListSequence.fromList(SNodeOperations.getNodeDescendants(_context.getNode(), CONCEPTS.ActionAsPattern$TP, false, new SAbstractConcept[]{})).isNotEmpty();
  }
  public static boolean ifMacro_Condition_7_0(final IfMacroContext _context) {
    return _context.getNode() != ((SNode) _context.getVariable("topNode"));
  }
  public static boolean ifMacro_Condition_7_1(final IfMacroContext _context) {
    // OrPatternClause is distinct case of PatternExpression, 
    // nested inside of the latter, and there's local variable we shall reference. 
    // PatternExpression owns Quotation, which in turn supplies quoted node == topNode, hence parent.parent 
    return _context.getNode() == ((SNode) _context.getVariable("topNode")) && SNodeOperations.isInstanceOf(SNodeOperations.getParent(SNodeOperations.getParent(_context.getNode())), CONCEPTS.OrPatternClause$W4);
  }
  public static boolean ifMacro_Condition_7_2(final IfMacroContext _context) {
    // (PatternExpression|OrPatternClause)->Quotation->topNode 
    return _context.getNode() == ((SNode) _context.getVariable("topNode")) && !(SNodeOperations.isInstanceOf(SNodeOperations.getParent(SNodeOperations.getParent(_context.getNode())), CONCEPTS.OrPatternClause$W4));
  }
  public static boolean ifMacro_Condition_9_0(final IfMacroContext _context) {
    return Sequence.fromIterable(((Iterable<SNode>) _context.getVariable("tail"))).isNotEmpty();
  }
  public static boolean ifMacro_Condition_13_0(final IfMacroContext _context) {
    return ListSequence.fromList(SNodeOperations.getNodeDescendants(_context.getNode(), CONCEPTS.NodeBuilderRef$az, false, new SAbstractConcept[]{})).isNotEmpty();
  }
  public static boolean ifMacro_Condition_16_0(final IfMacroContext _context) {
    return (boolean) PatternSwitchCase__BehaviorDescriptor.hasVariableReferences_id5sDn0OneX$C.invoke(_context.getNode());
  }
  public static boolean ifMacro_Condition_16_1(final IfMacroContext _context) {
    return ListSequence.fromList(SLinkOperations.getChildren(_context.getNode(), LINKS.case$nt1N)).isNotEmpty();
  }
  public static boolean ifMacro_Condition_16_2(final IfMacroContext _context) {
    return (boolean) PatternSwitchCase__BehaviorDescriptor.hasVariableReferences_id5sDn0OneX$C.invoke(_context.getNode());
  }
  public static SNode sourceNodeQuery_0_0(final SourceSubstituteMacroNodeContext _context) {
    return SLinkOperations.getTarget(_context.getNode(), LINKS.pattern$fJGl);
  }
  public static SNode sourceNodeQuery_0_1(final SourceSubstituteMacroNodeContext _context) {
    return SLinkOperations.getTarget(_context.getNode(), LINKS.pattern$m3eu);
  }
  public static SNode sourceNodeQuery_5_0(final SourceSubstituteMacroNodeContext _context) {
    return TypecheckingFacade.getFromContext().getTypeOf(SLinkOperations.getTarget(_context.getNode(), LINKS.variable$w5gw));
  }
  public static SNode sourceNodeQuery_7_0(final SourceSubstituteMacroNodeContext _context) {
    return SNodeOperations.getParent(_context.getNode());
  }
  public static SNode sourceNodeQuery_7_1(final SourceSubstituteMacroNodeContext _context) {
    SNode id = SConceptOperations.createNewNode(MetaAdapterFactory.getConcept(0x7866978ea0f04cc7L, 0x81bc4d213d9375e1L, 0x74cb131f5923b6e7L, "jetbrains.mps.lang.smodel.structure.ContainmentLinkId"));
    ContainmentLinkId__BehaviorDescriptor.setLink_id7jb4LXp8VsD.invoke(id, SNodeOperations.getContainingLink(_context.getNode()));
    return id;
  }
  public static SNode sourceNodeQuery_8_0(final SourceSubstituteMacroNodeContext _context) {
    return SNodeOperations.getParent(_context.getNode());
  }
  public static SNode sourceNodeQuery_8_1(final SourceSubstituteMacroNodeContext _context) {
    return SNodeOperations.getParent(_context.getNode());
  }
  public static SNode sourceNodeQuery_8_2(final SourceSubstituteMacroNodeContext _context) {
    SNode pid = SModelOperations.createNewNode(_context.getInputModel(), null, CONCEPTS.PropertyId$Ig);
    PropertyId__BehaviorDescriptor.setProperty_id5ZE7FBYZ2jW.invoke(pid, PropertyAttribute__BehaviorDescriptor.getProperty_id1avfQ4BBzOo.invoke(_context.getNode()));
    return pid;
  }
  public static SNode sourceNodeQuery_8_3(final SourceSubstituteMacroNodeContext _context) {
    return SNodeOperations.getParent(_context.getNode());
  }
  public static SNode sourceNodeQuery_8_4(final SourceSubstituteMacroNodeContext _context) {
    SNode id = SModelOperations.createNewNode(_context.getInputModel(), null, CONCEPTS.ReferenceLinkId$Ic);
    ReferenceLinkId__BehaviorDescriptor.setReference_id7jb4LXp9a6q.invoke(id, LinkAttribute__BehaviorDescriptor.getLink_id1avfQ4BEFo6.invoke(_context.getNode()));
    return id;

  }
  public static SNode sourceNodeQuery_8_5(final SourceSubstituteMacroNodeContext _context) {
    return SNodeOperations.getParent(_context.getNode());
  }
  public static SNode sourceNodeQuery_8_6(final SourceSubstituteMacroNodeContext _context) {
    return SNodeOperations.getParent(_context.getNode());
  }
  public static SNode sourceNodeQuery_8_7(final SourceSubstituteMacroNodeContext _context) {
    // OrPatternVariableReference is an Expression, not a NodeAttribute, 
    // thus we need accessor to this node, not its parent (as we do for Attributes) 
    return _context.getNode();
  }
  public static SNode sourceNodeQuery_8_8(final SourceSubstituteMacroNodeContext _context) {
    return ListSequence.fromList(((List<SNode>) _context.getVariable("var:disjunctClause"))).first();
  }
  public static SNode sourceNodeQuery_9_0(final SourceSubstituteMacroNodeContext _context) {
    // OrPattern is parent of OrPatternClause being processed, 
    // and is the one we shall navigate matcher to, if it's used in place for a node. 
    // however, the right way is to use it as attribute, thus we account for both cases 
    SNode orPattern = SNodeOperations.getParent(_context.getNode());
    return (SNodeOperations.isAttribute(orPattern) ? SNodeOperations.getParent(orPattern) : orPattern);
  }
  public static SNode sourceNodeQuery_9_1(final SourceSubstituteMacroNodeContext _context) {
    // handle next clause, pass the tail stripped of this value to the next level 
    return Sequence.fromIterable(((Iterable<SNode>) _context.getVariable("tail"))).first();
  }
  public static SNode sourceNodeQuery_11_0(final SourceSubstituteMacroNodeContext _context) {
    return SNodeOperations.getParent(_context.getNode());
  }
  public static SNode sourceNodeQuery_11_1(final SourceSubstituteMacroNodeContext _context) {
    // Here we assume ListPattern could not be applied to top-most node (as it needs a list of children, while quotation is single node) 
    SNode id = SConceptOperations.createNewNode(MetaAdapterFactory.getConcept(0x7866978ea0f04cc7L, 0x81bc4d213d9375e1L, 0x74cb131f5923b6e7L, "jetbrains.mps.lang.smodel.structure.ContainmentLinkId"));
    ContainmentLinkId__BehaviorDescriptor.setLink_id7jb4LXp8VsD.invoke(id, SNodeOperations.getContainingLink(_context.getNode()));
    return id;
  }
  public static SNode sourceNodeQuery_13_0(final SourceSubstituteMacroNodeContext _context) {
    return SLinkOperations.getTarget(_context.getNode(), LINKS.builder$Ubq1);
  }
  public static SNode sourceNodeQuery_13_1(final SourceSubstituteMacroNodeContext _context) {
    return _context.getNode();
  }
  public static SNode sourceNodeQuery_14_0(final SourceSubstituteMacroNodeContext _context) {
    return (SNode) LinkDeclaration__BehaviorDescriptor.getGenuineLink_idhEwIf_V.invoke(SLinkOperations.getTarget(_context.getNode(), LINKS.link$ckAZ));
  }
  public static SNode sourceNodeQuery_14_1(final SourceSubstituteMacroNodeContext _context) {
    return SLinkOperations.getTarget(_context.getNode(), LINKS.property$NCMw);
  }
  public static SNode sourceNodeQuery_14_2(final SourceSubstituteMacroNodeContext _context) {
    return SLinkOperations.getTarget(_context.getNode(), LINKS.link$ckAZ);
  }
  public static SNode sourceNodeQuery_16_0(final SourceSubstituteMacroNodeContext _context) {
    return SLinkOperations.getTarget(_context.getNode(), LINKS.expression$nt1k);
  }
  public static SNode sourceNodeQuery_16_1(final SourceSubstituteMacroNodeContext _context) {
    return _context.getNode();
  }
  public static SNode sourceNodeQuery_16_2(final SourceSubstituteMacroNodeContext _context) {
    return SLinkOperations.getTarget(ListSequence.fromList(SLinkOperations.getChildren(_context.getNode(), LINKS.case$nt1N)).first(), LINKS.body$6jgq);
  }
  public static SNode sourceNodeQuery_16_3(final SourceSubstituteMacroNodeContext _context) {
    return SLinkOperations.getTarget(_context.getNode(), LINKS.body$6jgq);
  }
  public static SNode sourceNodeQuery_16_4(final SourceSubstituteMacroNodeContext _context) {
    return SLinkOperations.getTarget(_context.getNode(), LINKS.pattern$LFiH);
  }
  public static SNode sourceNodeQuery_16_5(final SourceSubstituteMacroNodeContext _context) {
    return SLinkOperations.getTarget(_context.getNode(), LINKS.pattern$LFiH);
  }
  public static SNode sourceNodeQuery_16_6(final SourceSubstituteMacroNodeContext _context) {
    return SLinkOperations.getTarget(_context.getNode(), LINKS.defaultBlock$twKh);
  }
  public static SNode sourceNodeQuery_16_7(final SourceSubstituteMacroNodeContext _context) {
    return SLinkOperations.getTarget(_context.getNode(), LINKS.pattern$LFiH);
  }
  public static SNode sourceNodeQuery_16_8(final SourceSubstituteMacroNodeContext _context) {
    return ListSequence.fromList(SLinkOperations.getChildren(_context.getNode(), LINKS.case$nt1N)).first();
  }
  public static SNode sourceNodeQuery_16_9(final SourceSubstituteMacroNodeContext _context) {
    return SLinkOperations.getTarget(_context.getNode(), LINKS.pattern$LFiH);
  }
  public static SNode sourceNodeQuery_17_0(final SourceSubstituteMacroNodeContext _context) {
    return SLinkOperations.getTarget(_context.getNode(), LINKS.pattern$65eZ);
  }
  public static Object templateArgumentQuery_13_0(final TemplateArgumentContext _context) {
    return SNodeOperations.as(SNodeOperations.getParent(_context.getNode()), CONCEPTS.NodeBuilderNode$RN);
  }
  public static Object templateArgumentQuery_0_0(final TemplateArgumentContext _context) {
    return NameUtil.capitalize(SPropertyOperations.getString(_context.getNode(), PROPS.name$tAp1)) + "_Pattern";
  }
  public static Object templateArgumentQuery_8_0(final TemplateArgumentContext _context) {
    return ListSequence.fromList(((List<SNode>) _context.getVariable("var:disjunctClause"))).skip(1);
  }
  public static Object templateArgumentQuery_9_0(final TemplateArgumentContext _context) {
    return Sequence.fromIterable(((Iterable<SNode>) _context.getVariable("tail"))).skip(1);
  }
  public static Object templateArgumentQuery_17_0(final TemplateArgumentContext _context) {
    return _context.createUniqueName("Pattern", ListSequence.fromList(SNodeOperations.getNodeAncestors(_context.getNode(), CONCEPTS.Classifier$hJ, false)).last());
  }
  public static Object templateArgumentQuery_13_1(final TemplateArgumentContext _context) {
    return Optional.<Boolean>empty();
  }
  public static Iterable<SNode> sourceNodesQuery_0_0(final SourceSubstituteMacroNodesContext _context) {
    return SLinkOperations.collect(SLinkOperations.collectMany(SNodeOperations.getNodeDescendants(_context.getNode(), CONCEPTS.OrPattern$zL, false, new SAbstractConcept[]{}), LINKS.clause$j$BB), LINKS.pattern$fJGl);
  }
  public static Iterable<SNode> sourceNodesQuery_6_0(final SourceSubstituteMacroNodesContext _context) {
    // NOTE: DO NOT TRY TO SET MappingLabel here, leave it at nested, as we need 
    // LocalVariableDeclaration, not LVDStatement as 
    return ((Iterable<SNode>) _context.getVariable("var:disjunctionPatterns"));
  }
  public static Iterable<SNode> sourceNodesQuery_6_1(final SourceSubstituteMacroNodesContext _context) {
    return ((Iterable<SNode>) _context.getVariable("var:disjunctionPatterns"));
  }
  public static Iterable<SNode> sourceNodesQuery_6_2(final SourceSubstituteMacroNodesContext _context) {
    return ((Iterable<SNode>) _context.getVariable("var:disjunctionPatterns"));
  }
  public static Iterable<SNode> sourceNodesQuery_6_3(final SourceSubstituteMacroNodesContext _context) {
    return SLinkOperations.collect(SNodeOperations.getNodeDescendants(_context.getNode(), CONCEPTS.ActionAsPattern$TP, false, new SAbstractConcept[]{}), LINKS.action$dtRs);
  }
  public static Iterable<SNode> sourceNodesQuery_10_0(final SourceSubstituteMacroNodesContext _context) {
    // under OrPattern, they use OrPatternVariableReference to capture values instead of PatternVariableDeclaration used elsewhere 
    // (declarations are owned by OrPattern instance). Don't blame me, this is the way someone else think is smart 

    // We don't go deeper than OrPattern as there's distinct handling for OrPatternClause (which effectively excludes PVD under OrPattern) 
    // Since it ends here, in this template, we look for OrPatternVariableReference right away. 
    List<SNode> d = SNodeOperations.getNodeDescendantsWhereConceptInList(((SNode) _context.getVariable("var:quotedNode")), new SAbstractConcept[]{CONCEPTS.Pattern$Ke, CONCEPTS.PropertyPatternVariableDeclaration$Xj, CONCEPTS.LinkPatternVariableDeclaration$UB, CONCEPTS.OrPatternVariableReference$At}, false, new SAbstractConcept[]{CONCEPTS.OrPattern$zL});
    Iterable<SNode> orPattern = SNodeOperations.getNodeDescendants(((SNode) _context.getVariable("var:quotedNode")), CONCEPTS.OrPattern$zL, false, new SAbstractConcept[]{});
    return ListSequence.fromList(d).union(Sequence.fromIterable(orPattern));
  }
  public static Iterable<SNode> sourceNodesQuery_13_0(final SourceSubstituteMacroNodesContext _context) {
    return (List<SNode>) PatternBuilder__BehaviorDescriptor.getNodeVariables_id2g69lt1CX0k.invoke(_context.getNode());
  }
  public static Iterable<SNode> sourceNodesQuery_13_1(final SourceSubstituteMacroNodesContext _context) {
    return (List<SNode>) PatternBuilder__BehaviorDescriptor.getPropertyVariables_id1tcvH6au_W4.invoke(_context.getNode());
  }
  public static Iterable<SNode> sourceNodesQuery_13_2(final SourceSubstituteMacroNodesContext _context) {
    return Sequence.fromIterable(NodeBuilderNode__BehaviorDescriptor.getExternalExpressions_idRRzwLnBxZy.invoke(SLinkOperations.getTarget(_context.getNode(), LINKS.builder$Ubq1))).where(new IWhereFilter<SNode>() {
      public boolean accept(SNode it) {
        return SNodeOperations.hasRole(it, LINKS.expression$JCaZ) && SNodeOperations.hasRole(SNodeOperations.getParent(it), LINKS.initValue$UJfh) && SEnumOperations.isMember(SPropertyOperations.getEnum(SLinkOperations.getTarget(SNodeOperations.cast(SNodeOperations.getParent(SNodeOperations.getParent(it)), CONCEPTS.NodeBuilderInitLink$Xj), LINKS.link$ckAZ), PROPS.metaClass$tHD7), 0xfc6f4e95b8L);
      }
    });
  }
  public static Iterable<SNode> sourceNodesQuery_13_3(final SourceSubstituteMacroNodesContext _context) {
    return SLinkOperations.getChildren(_context.getNode(), LINKS.smodelAttribute$K8bJ);
  }
  public static Iterable<SNode> sourceNodesQuery_13_4(final SourceSubstituteMacroNodesContext _context) {
    return Sequence.fromIterable(NodeBuilderNode__BehaviorDescriptor.getExternalExpressions_idRRzwLnBxZy.invoke(SLinkOperations.getTarget(_context.getNode(), LINKS.builder$Ubq1))).where(new IWhereFilter<SNode>() {
      public boolean accept(SNode it) {
        return SNodeOperations.hasRole(it, LINKS.expression$JCaZ) && SNodeOperations.hasRole(SNodeOperations.getParent(it), LINKS.initValue$UJfh) && SEnumOperations.isMember(SPropertyOperations.getEnum(SLinkOperations.getTarget(SNodeOperations.cast(SNodeOperations.getParent(SNodeOperations.getParent(it)), CONCEPTS.NodeBuilderInitLink$Xj), LINKS.link$ckAZ), PROPS.metaClass$tHD7), 0xfc6f4e95b8L);
      }
    });
  }
  public static Iterable<SNode> sourceNodesQuery_13_5(final SourceSubstituteMacroNodesContext _context) {
    return Sequence.fromIterable(NodeBuilderNode__BehaviorDescriptor.getExternalExpressions_idRRzwLnBxZy.invoke(SLinkOperations.getTarget(_context.getNode(), LINKS.builder$Ubq1))).where(new IWhereFilter<SNode>() {
      public boolean accept(SNode it) {
        return SNodeOperations.hasRole(it, LINKS.initValue$nhHN);
      }
    });
  }
  public static Iterable<SNode> sourceNodesQuery_13_6(final SourceSubstituteMacroNodesContext _context) {
    return Sequence.fromIterable(NodeBuilderNode__BehaviorDescriptor.getExternalExpressions_idRRzwLnBxZy.invoke(SLinkOperations.getTarget(_context.getNode(), LINKS.builder$Ubq1))).where(new IWhereFilter<SNode>() {
      public boolean accept(SNode it) {
        return SNodeOperations.hasRole(it, LINKS.expression$JCaZ) && SNodeOperations.hasRole(SNodeOperations.getParent(it), LINKS.initValue$UJfh) && SEnumOperations.isMember(SPropertyOperations.getEnum(SLinkOperations.getTarget(SNodeOperations.cast(SNodeOperations.getParent(SNodeOperations.getParent(it)), CONCEPTS.NodeBuilderInitLink$Xj), LINKS.link$ckAZ), PROPS.metaClass$tHD7), 0xfc6f4e95b8L);
      }
    });
  }
  public static Iterable<SNode> sourceNodesQuery_13_7(final SourceSubstituteMacroNodesContext _context) {
    return Sequence.fromIterable(NodeBuilderNode__BehaviorDescriptor.getExternalExpressions_idRRzwLnBxZy.invoke(SLinkOperations.getTarget(_context.getNode(), LINKS.builder$Ubq1))).where(new IWhereFilter<SNode>() {
      public boolean accept(SNode it) {
        return SNodeOperations.hasRole(it, LINKS.initValue$nhHN);
      }
    });
  }
  public static Iterable<SNode> sourceNodesQuery_13_8(final SourceSubstituteMacroNodesContext _context) {
    return SLinkOperations.getChildren(SLinkOperations.getTarget(_context.getNode(), LINKS.builder$Ubq1), LINKS.values$oju9);
  }
  public static Iterable<SNode> sourceNodesQuery_13_9(final SourceSubstituteMacroNodesContext _context) {
    return (List<SNode>) PatternBuilder__BehaviorDescriptor.getNodeVariables_id2g69lt1CX0k.invoke(_context.getNode());
  }
  public static Iterable<SNode> sourceNodesQuery_13_10(final SourceSubstituteMacroNodesContext _context) {
    return (List<SNode>) PatternBuilder__BehaviorDescriptor.getPropertyVariables_id1tcvH6au_W4.invoke(_context.getNode());
  }
  public static Iterable<SNode> sourceNodesQuery_16_0(final SourceSubstituteMacroNodesContext _context) {
    return ListSequence.fromList(SLinkOperations.getChildren(_context.getNode(), LINKS.case$nt1N)).where(new IWhereFilter<SNode>() {
      public boolean accept(SNode cs) {
        return (boolean) PatternSwitchCase__BehaviorDescriptor.hasVariableReferences_id5sDn0OneX$C.invoke(cs);
      }
    }).select(new ISelector<SNode, SNode>() {
      public SNode select(SNode it) {
        return SLinkOperations.getTarget(it, LINKS.pattern$LFiH);
      }
    });
  }
  public static Iterable<SNode> sourceNodesQuery_16_1(final SourceSubstituteMacroNodesContext _context) {
    return ListSequence.fromList(SLinkOperations.getChildren(_context.getNode(), LINKS.case$nt1N)).skip(1);
  }
  public static Iterable<SNode> sourceNodesQuery_16_2(final SourceSubstituteMacroNodesContext _context) {
    return SLinkOperations.getChildren(SLinkOperations.getTarget(_context.getNode(), LINKS.defaultBlock$twKh), LINKS.statement$WHn8);
  }
  public static Iterable<SNode> sourceNodesQuery_17_0(final SourceSubstituteMacroNodesContext _context) {
    return Sequence.fromIterable(NodeBuilderNode__BehaviorDescriptor.getExternalExpressions_idRRzwLnBxZy.invoke(SLinkOperations.getTarget(SLinkOperations.getTarget(SLinkOperations.getTarget(_context.getNode(), LINKS.declaration$6hl0), LINKS.pattern$m3eu), LINKS.builder$Ubq1))).where(new IWhereFilter<SNode>() {
      public boolean accept(SNode it) {
        return SNodeOperations.hasRole(it, LINKS.expression$JCaZ) && SNodeOperations.hasRole(SNodeOperations.getParent(it), LINKS.initValue$UJfh) && SEnumOperations.isMember(SPropertyOperations.getEnum(SLinkOperations.getTarget(SNodeOperations.cast(SNodeOperations.getParent(SNodeOperations.getParent(it)), CONCEPTS.NodeBuilderInitLink$Xj), LINKS.link$ckAZ), PROPS.metaClass$tHD7), 0xfc6f4e95b8L);
      }
    });
  }
  public static Iterable<SNode> sourceNodesQuery_17_1(final SourceSubstituteMacroNodesContext _context) {
    return Sequence.fromIterable(NodeBuilderNode__BehaviorDescriptor.getExternalExpressions_idRRzwLnBxZy.invoke(SLinkOperations.getTarget(SLinkOperations.getTarget(SLinkOperations.getTarget(_context.getNode(), LINKS.declaration$6hl0), LINKS.pattern$m3eu), LINKS.builder$Ubq1))).where(new IWhereFilter<SNode>() {
      public boolean accept(SNode it) {
        return SNodeOperations.hasRole(it, LINKS.initValue$nhHN);
      }
    });
  }
  public static Iterable<SNode> sourceNodesQuery_17_2(final SourceSubstituteMacroNodesContext _context) {
    return Sequence.fromIterable(NodeBuilderNode__BehaviorDescriptor.getExternalExpressions_idRRzwLnBxZy.invoke(SLinkOperations.getTarget(SLinkOperations.getTarget(_context.getNode(), LINKS.pattern$65eZ), LINKS.builder$Ubq1))).where(new IWhereFilter<SNode>() {
      public boolean accept(SNode it) {
        return SNodeOperations.hasRole(it, LINKS.expression$JCaZ) && SNodeOperations.hasRole(SNodeOperations.getParent(it), LINKS.initValue$UJfh) && SEnumOperations.isMember(SPropertyOperations.getEnum(SLinkOperations.getTarget(SNodeOperations.cast(SNodeOperations.getParent(SNodeOperations.getParent(it)), CONCEPTS.NodeBuilderInitLink$Xj), LINKS.link$ckAZ), PROPS.metaClass$tHD7), 0xfc6f4e95b8L);
      }
    });
  }
  public static Iterable<SNode> sourceNodesQuery_17_3(final SourceSubstituteMacroNodesContext _context) {
    return Sequence.fromIterable(NodeBuilderNode__BehaviorDescriptor.getExternalExpressions_idRRzwLnBxZy.invoke(SLinkOperations.getTarget(SLinkOperations.getTarget(_context.getNode(), LINKS.pattern$65eZ), LINKS.builder$Ubq1))).where(new IWhereFilter<SNode>() {
      public boolean accept(SNode it) {
        return SNodeOperations.hasRole(it, LINKS.initValue$nhHN);
      }
    });
  }
  public static Object varMacro_Value_6_0(final TemplateVarContext _context) {
    return SLinkOperations.collectMany(SNodeOperations.getNodeDescendants(_context.getNode(), CONCEPTS.OrPattern$zL, false, new SAbstractConcept[]{}), LINKS.clause$j$BB);
  }
  public static Object varMacro_Value_8_0(final TemplateVarContext _context) {
    // nature of template language dictates generation from right to left 
    // while order of disjunct registration shall match that in the model 
    return ListSequence.fromList(SLinkOperations.getChildren(_context.getNode(), LINKS.clause$j$BB)).reversedList();
  }
  public static Object varMacro_Value_10_0(final TemplateVarContext _context) {
    return SLinkOperations.getTarget(SLinkOperations.getTarget(_context.getNode(), LINKS.pattern$fJGl), LINKS.quotedNode$kInw);
  }
  private final Map<String, ReductionRuleCondition> rrcMethods = new HashMap<String, ReductionRuleCondition>();
  {
    int i = 0;
    rrcMethods.put("3159668873483304935", new RRC(i++));
    rrcMethods.put("1678856199547609437", new RRC(i++));
    rrcMethods.put("6280652366637209338", new RRC(i++));
    rrcMethods.put("6280652366639334117", new RRC(i++));
    rrcMethods.put("6280652366639956026", new RRC(i++));
    rrcMethods.put("9046399079000879902", new RRC(i++));
    rrcMethods.put("2595803291918874274", new RRC(i++));
    rrcMethods.put("5756354288101425578", new RRC(i++));
    rrcMethods.put("1678856199538865949", new RRC(i++));
    rrcMethods.put("1678856199539215516", new RRC(i++));
  }
  @Override
  @NotNull
  public ReductionRuleCondition getReductionRuleCondition(@NotNull QueryKey identity) {
    final String id = identity.getTemplateNode().getNodeId().toString();
    if (!(rrcMethods.containsKey(id))) {
      return super.getReductionRuleCondition(identity);
    }
    return rrcMethods.get(id);
  }
  private static class RRC implements ReductionRuleCondition {
    private final int methodKey;
    public RRC(int methodKey) {
      this.methodKey = methodKey;
    }
    @Override
    public boolean check(ReductionRuleQueryContext ctx) throws GenerationFailureException {
      switch (methodKey) {
        case 0:
          return QueriesGenerated.rule_Condition_0_1(ctx);
        case 1:
          return QueriesGenerated.rule_Condition_0_2(ctx);
        case 2:
          return QueriesGenerated.rule_Condition_0_3(ctx);
        case 3:
          return QueriesGenerated.rule_Condition_0_4(ctx);
        case 4:
          return QueriesGenerated.rule_Condition_0_5(ctx);
        case 5:
          return QueriesGenerated.rule_Condition_8_0(ctx);
        case 6:
          return QueriesGenerated.rule_Condition_12_0(ctx);
        case 7:
          return QueriesGenerated.rule_Condition_14_0(ctx);
        case 8:
          return QueriesGenerated.rule_Condition_14_1(ctx);
        case 9:
          return QueriesGenerated.rule_Condition_14_2(ctx);
        default:
          throw new GenerationFailureException(String.format("Inconsistent QueriesGenerated: there's no condition method for rule %s (key: #%d)", ctx.getTemplateReference(), methodKey));
      }
    }
  }
  private final Map<String, MapRootRuleCondition> mrrcMethods = new HashMap<String, MapRootRuleCondition>();
  {
    int i = 0;
    mrrcMethods.put("9046399079000776306", new MRRC(i++));
  }
  @Override
  @NotNull
  public MapRootRuleCondition getMapRootRuleCondition(@NotNull QueryKey identity) {
    final String id = identity.getTemplateNode().getNodeId().toString();
    if (!(mrrcMethods.containsKey(id))) {
      return super.getMapRootRuleCondition(identity);
    }
    return mrrcMethods.get(id);
  }
  private static class MRRC implements MapRootRuleCondition {
    private final int methodKey;
    public MRRC(int methodKey) {
      this.methodKey = methodKey;
    }
    @Override
    public boolean check(@NotNull MapRootRuleContext ctx) throws GenerationFailureException {
      switch (methodKey) {
        case 0:
          return QueriesGenerated.rule_Condition_0_0(ctx);
        default:
          throw new GenerationFailureException(String.format("Inconsistent QueriesGenerated: there's no condition method for rule %s (key: #%d)", ctx.getTemplateReference(), methodKey));
      }
    }
  }
  private final Map<String, DropAttributeRuleCondition> darcMethods = new HashMap<String, DropAttributeRuleCondition>();
  {
    int i = 0;
    darcMethods.put("6930688547477894224", new DARC(i++));
    darcMethods.put("6930688547477894546", new DARC(i++));
    darcMethods.put("2056074660033127915", new DARC(i++));
    darcMethods.put("2056074660033131215", new DARC(i++));
    darcMethods.put("6930688547477945553", new DARC(i++));
  }
  @Override
  @NotNull
  public DropAttributeRuleCondition getDropAttributeRuleCondition(@NotNull QueryKey identity) {
    final String id = identity.getTemplateNode().getNodeId().toString();
    if (!(darcMethods.containsKey(id))) {
      return super.getDropAttributeRuleCondition(identity);
    }
    return darcMethods.get(id);
  }
  private static class DARC implements DropAttributeRuleCondition {
    private final int methodKey;
    public DARC(int methodKey) {
      this.methodKey = methodKey;
    }
    @Override
    public boolean check(@NotNull DropAttributeRuleContext ctx) throws GenerationFailureException {
      switch (methodKey) {
        case 0:
          return QueriesGenerated.dropAttr_Condition_0_0(ctx);
        case 1:
          return QueriesGenerated.dropAttr_Condition_0_1(ctx);
        case 2:
          return QueriesGenerated.dropAttr_Condition_0_2(ctx);
        case 3:
          return QueriesGenerated.dropAttr_Condition_0_3(ctx);
        case 4:
          return QueriesGenerated.dropAttr_Condition_0_4(ctx);
        default:
          throw new GenerationFailureException(String.format("Inconsistent QueriesGenerated: there's no condition method for rule %s (key: #%d)", ctx.getTemplateReference(), methodKey));
      }
    }
  }
  private final Map<String, SourceNodeQuery> snqMethods = new HashMap<String, SourceNodeQuery>();
  {
    int i = 0;
    snqMethods.put("6930688547477853548", new SNQ(i++));
    snqMethods.put("3741790230811385340", new SNQ(i++));
    snqMethods.put("7236394192440107561", new SNQ(i++));
    snqMethods.put("1949222934982669673", new SNQ(i++));
    snqMethods.put("5495892681292567294", new SNQ(i++));
    snqMethods.put("7503628237557099095", new SNQ(i++));
    snqMethods.put("7503628237557111882", new SNQ(i++));
    snqMethods.put("9046399079000873736", new SNQ(i++));
    snqMethods.put("7503628237557078871", new SNQ(i++));
    snqMethods.put("7503628237557076403", new SNQ(i++));
    snqMethods.put("6837177972706217257", new SNQ(i++));
    snqMethods.put("7503628237557096707", new SNQ(i++));
    snqMethods.put("1949222934982326306", new SNQ(i++));
    snqMethods.put("1949222934982505748", new SNQ(i++));
    snqMethods.put("1949222934982452091", new SNQ(i++));
    snqMethods.put("1949222934982455123", new SNQ(i++));
    snqMethods.put("5149262387754026894", new SNQ(i++));
    snqMethods.put("5495892681292543908", new SNQ(i++));
    snqMethods.put("1724959616550687264", new SNQ(i++));
    snqMethods.put("2595803291918535210", new SNQ(i++));
    snqMethods.put("5756354288101153800", new SNQ(i++));
    snqMethods.put("1678856199538870988", new SNQ(i++));
    snqMethods.put("1678856199539215559", new SNQ(i++));
    snqMethods.put("1678856199547632378", new SNQ(i++));
    snqMethods.put("8950533135209526023", new SNQ(i++));
    snqMethods.put("1678856199547954037", new SNQ(i++));
    snqMethods.put("1678856199547972144", new SNQ(i++));
    snqMethods.put("2793477601721485880", new SNQ(i++));
    snqMethods.put("6280652366639064772", new SNQ(i++));
    snqMethods.put("1678856199547984724", new SNQ(i++));
    snqMethods.put("2793477601721476407", new SNQ(i++));
    snqMethods.put("6280652366639042175", new SNQ(i++));
    snqMethods.put("6280652366639061110", new SNQ(i++));
    snqMethods.put("8950533135208546533", new SNQ(i++));
  }
  @NotNull
  @Override
  public SourceNodeQuery getSourceNodeQuery(@NotNull QueryKey identity) {
    final String id = ((QueryKeyImpl) identity).getQueryNodeId().toString();
    if (!(snqMethods.containsKey(id))) {
      return super.getSourceNodeQuery(identity);
    }
    return snqMethods.get(id);
  }
  private static class SNQ implements SourceNodeQuery {
    private final int methodKey;
    public SNQ(int methodKey) {
      this.methodKey = methodKey;
    }
    @Nullable
    public SNode evaluate(@NotNull SourceSubstituteMacroNodeContext ctx) throws GenerationFailureException {
      switch (methodKey) {
        case 0:
          return QueriesGenerated.sourceNodeQuery_0_0(ctx);
        case 1:
          return QueriesGenerated.sourceNodeQuery_0_1(ctx);
        case 2:
          return QueriesGenerated.sourceNodeQuery_5_0(ctx);
        case 3:
          return QueriesGenerated.sourceNodeQuery_7_0(ctx);
        case 4:
          return QueriesGenerated.sourceNodeQuery_7_1(ctx);
        case 5:
          return QueriesGenerated.sourceNodeQuery_8_0(ctx);
        case 6:
          return QueriesGenerated.sourceNodeQuery_8_1(ctx);
        case 7:
          return QueriesGenerated.sourceNodeQuery_8_2(ctx);
        case 8:
          return QueriesGenerated.sourceNodeQuery_8_3(ctx);
        case 9:
          return QueriesGenerated.sourceNodeQuery_8_4(ctx);
        case 10:
          return QueriesGenerated.sourceNodeQuery_8_5(ctx);
        case 11:
          return QueriesGenerated.sourceNodeQuery_8_6(ctx);
        case 12:
          return QueriesGenerated.sourceNodeQuery_8_7(ctx);
        case 13:
          return QueriesGenerated.sourceNodeQuery_8_8(ctx);
        case 14:
          return QueriesGenerated.sourceNodeQuery_9_0(ctx);
        case 15:
          return QueriesGenerated.sourceNodeQuery_9_1(ctx);
        case 16:
          return QueriesGenerated.sourceNodeQuery_11_0(ctx);
        case 17:
          return QueriesGenerated.sourceNodeQuery_11_1(ctx);
        case 18:
          return QueriesGenerated.sourceNodeQuery_13_0(ctx);
        case 19:
          return QueriesGenerated.sourceNodeQuery_13_1(ctx);
        case 20:
          return QueriesGenerated.sourceNodeQuery_14_0(ctx);
        case 21:
          return QueriesGenerated.sourceNodeQuery_14_1(ctx);
        case 22:
          return QueriesGenerated.sourceNodeQuery_14_2(ctx);
        case 23:
          return QueriesGenerated.sourceNodeQuery_16_0(ctx);
        case 24:
          return QueriesGenerated.sourceNodeQuery_16_1(ctx);
        case 25:
          return QueriesGenerated.sourceNodeQuery_16_2(ctx);
        case 26:
          return QueriesGenerated.sourceNodeQuery_16_3(ctx);
        case 27:
          return QueriesGenerated.sourceNodeQuery_16_4(ctx);
        case 28:
          return QueriesGenerated.sourceNodeQuery_16_5(ctx);
        case 29:
          return QueriesGenerated.sourceNodeQuery_16_6(ctx);
        case 30:
          return QueriesGenerated.sourceNodeQuery_16_7(ctx);
        case 31:
          return QueriesGenerated.sourceNodeQuery_16_8(ctx);
        case 32:
          return QueriesGenerated.sourceNodeQuery_16_9(ctx);
        case 33:
          return QueriesGenerated.sourceNodeQuery_17_0(ctx);
        default:
          throw new GenerationFailureException(String.format("Inconsistent QueriesGenerated: there's no method for query %s (key: #%d)", ctx.getTemplateReference(), methodKey));
      }
    }
  }
  private final Map<String, SourceNodesQuery> snsqMethods = new HashMap<String, SourceNodesQuery>();
  {
    int i = 0;
    snsqMethods.put("1949222934982779314", new SNsQ(i++));
    snsqMethods.put("1949222934982395853", new SNsQ(i++));
    snsqMethods.put("1949222934982712250", new SNsQ(i++));
    snsqMethods.put("1949222934982556571", new SNsQ(i++));
    snsqMethods.put("1949222934982158653", new SNsQ(i++));
    snsqMethods.put("1949222934982630106", new SNsQ(i++));
    snsqMethods.put("2595803291919271595", new SNsQ(i++));
    snsqMethods.put("1678856199538898480", new SNsQ(i++));
    snsqMethods.put("3741790230811224191", new SNsQ(i++));
    snsqMethods.put("3741790230811227337", new SNsQ(i++));
    snsqMethods.put("2760023158765551414", new SNsQ(i++));
    snsqMethods.put("2760023158766425974", new SNsQ(i++));
    snsqMethods.put("3741790230811210777", new SNsQ(i++));
    snsqMethods.put("3741790230811214089", new SNsQ(i++));
    snsqMethods.put("8642609567145868975", new SNsQ(i++));
    snsqMethods.put("2595803291919303998", new SNsQ(i++));
    snsqMethods.put("1678856199538903693", new SNsQ(i++));
    snsqMethods.put("8950533135209361432", new SNsQ(i++));
    snsqMethods.put("1678856199547894476", new SNsQ(i++));
    snsqMethods.put("1678856199549438112", new SNsQ(i++));
    snsqMethods.put("2793477601721455459", new SNsQ(i++));
    snsqMethods.put("2793477601721455505", new SNsQ(i++));
    snsqMethods.put("8950533135209624221", new SNsQ(i++));
    snsqMethods.put("8950533135209624267", new SNsQ(i++));
  }
  @NotNull
  @Override
  public SourceNodesQuery getSourceNodesQuery(@NotNull QueryKey identity) {
    final String id = ((QueryKeyImpl) identity).getQueryNodeId().toString();
    if (!(snsqMethods.containsKey(id))) {
      return super.getSourceNodesQuery(identity);
    }
    return snsqMethods.get(id);
  }
  private static class SNsQ implements SourceNodesQuery {
    private final int methodKey;
    public SNsQ(int methodKey) {
      this.methodKey = methodKey;
    }
    @NotNull
    public Collection<SNode> evaluate(@NotNull SourceSubstituteMacroNodesContext ctx) throws GenerationFailureException {
      switch (methodKey) {
        case 0:
          return IterableUtil.asCollection(QueriesGenerated.sourceNodesQuery_0_0(ctx));
        case 1:
          return IterableUtil.asCollection(QueriesGenerated.sourceNodesQuery_6_0(ctx));
        case 2:
          return IterableUtil.asCollection(QueriesGenerated.sourceNodesQuery_6_1(ctx));
        case 3:
          return IterableUtil.asCollection(QueriesGenerated.sourceNodesQuery_6_2(ctx));
        case 4:
          return IterableUtil.asCollection(QueriesGenerated.sourceNodesQuery_6_3(ctx));
        case 5:
          return IterableUtil.asCollection(QueriesGenerated.sourceNodesQuery_10_0(ctx));
        case 6:
          return IterableUtil.asCollection(QueriesGenerated.sourceNodesQuery_13_0(ctx));
        case 7:
          return IterableUtil.asCollection(QueriesGenerated.sourceNodesQuery_13_1(ctx));
        case 8:
          return IterableUtil.asCollection(QueriesGenerated.sourceNodesQuery_13_2(ctx));
        case 9:
          return IterableUtil.asCollection(QueriesGenerated.sourceNodesQuery_13_3(ctx));
        case 10:
          return IterableUtil.asCollection(QueriesGenerated.sourceNodesQuery_13_4(ctx));
        case 11:
          return IterableUtil.asCollection(QueriesGenerated.sourceNodesQuery_13_5(ctx));
        case 12:
          return IterableUtil.asCollection(QueriesGenerated.sourceNodesQuery_13_6(ctx));
        case 13:
          return IterableUtil.asCollection(QueriesGenerated.sourceNodesQuery_13_7(ctx));
        case 14:
          return IterableUtil.asCollection(QueriesGenerated.sourceNodesQuery_13_8(ctx));
        case 15:
          return IterableUtil.asCollection(QueriesGenerated.sourceNodesQuery_13_9(ctx));
        case 16:
          return IterableUtil.asCollection(QueriesGenerated.sourceNodesQuery_13_10(ctx));
        case 17:
          return IterableUtil.asCollection(QueriesGenerated.sourceNodesQuery_16_0(ctx));
        case 18:
          return IterableUtil.asCollection(QueriesGenerated.sourceNodesQuery_16_1(ctx));
        case 19:
          return IterableUtil.asCollection(QueriesGenerated.sourceNodesQuery_16_2(ctx));
        case 20:
          return IterableUtil.asCollection(QueriesGenerated.sourceNodesQuery_17_0(ctx));
        case 21:
          return IterableUtil.asCollection(QueriesGenerated.sourceNodesQuery_17_1(ctx));
        case 22:
          return IterableUtil.asCollection(QueriesGenerated.sourceNodesQuery_17_2(ctx));
        case 23:
          return IterableUtil.asCollection(QueriesGenerated.sourceNodesQuery_17_3(ctx));
        default:
          throw new GenerationFailureException(String.format("Inconsistent QueriesGenerated: there's no method for query %s (key: #%d)", ctx.getTemplateReference(), methodKey));
      }
    }
  }
  private final Map<String, PropertyValueQuery> pvqMethods = new HashMap<String, PropertyValueQuery>();
  {
    int i = 0;
    pvqMethods.put("7236394192440107543", new PVQ(i++, MetaAdapterFactory.getProperty(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf93d565d10L, 0xf93d565d11L, "value"), "ab"));
    pvqMethods.put("1949222934982218927", new PVQ(i++, MetaAdapterFactory.getProperty(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf8cc56b201L, 0xf8cc56b202L, "value"), "false"));
    pvqMethods.put("1949222934982397373", new PVQ(i++, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"), "disjunct"));
    pvqMethods.put("1949222934982557367", new PVQ(i++, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"), "orClause"));
    pvqMethods.put("9046399079000821218", new PVQ(i++, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"), "map_PatternExpression"));
    pvqMethods.put("1949222934982669693", new PVQ(i++, MetaAdapterFactory.getProperty(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf8cc59b314L, 0xf8cc59b315L, "value"), "0"));
    pvqMethods.put("7503628237557099104", new PVQ(i++, MetaAdapterFactory.getProperty(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf93d565d10L, 0xf93d565d11L, "value"), ""));
    pvqMethods.put("9046399079000871437", new PVQ(i++, MetaAdapterFactory.getProperty(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf93d565d10L, 0xf93d565d11L, "value"), ""));
    pvqMethods.put("7503628237557074993", new PVQ(i++, MetaAdapterFactory.getProperty(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf93d565d10L, 0xf93d565d11L, "value"), ""));
    pvqMethods.put("7503628237557097656", new PVQ(i++, MetaAdapterFactory.getProperty(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf93d565d10L, 0xf93d565d11L, "value"), ""));
    pvqMethods.put("1949222934982326315", new PVQ(i++, MetaAdapterFactory.getProperty(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf93d565d10L, 0xf93d565d11L, "value"), ""));
    pvqMethods.put("2595803291919315826", new PVQ(i++, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"), "myVar"));
    pvqMethods.put("1678856199538898487", new PVQ(i++, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"), "myVar"));
    pvqMethods.put("3741790230811226146", new PVQ(i++, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"), "myNodeParam"));
    pvqMethods.put("3741790230811228347", new PVQ(i++, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"), "myPropParam"));
    pvqMethods.put("2760023158765551404", new PVQ(i++, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"), "nodeParam"));
    pvqMethods.put("2760023158766425964", new PVQ(i++, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"), "propParam"));
    pvqMethods.put("2595803291919325663", new PVQ(i++, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"), "getVar"));
    pvqMethods.put("1678856199538903681", new PVQ(i++, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"), "getVar"));
    pvqMethods.put("3741790230811311179", new PVQ(i++, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"), "GeneratedPattern"));
    pvqMethods.put("1678856199548576288", new PVQ(i++, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"), "nodeToMatch"));
    pvqMethods.put("8950533135209355636", new PVQ(i++, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"), "pattern"));
  }
  @NotNull
  @Override
  public PropertyValueQuery getPropertyValueQuery(@NotNull QueryKey identity) {
    final String id = identity.getTemplateNode().getNodeId().toString();
    if (!(pvqMethods.containsKey(id))) {
      return super.getPropertyValueQuery(identity);
    }
    return pvqMethods.get(id);
  }
  private static class PVQ extends PropertyValueQuery.Base {
    private final int methodKey;
    /*package*/ PVQ(int methodKey, SProperty property, String templateValue) {
      super(property, templateValue);
      this.methodKey = methodKey;
    }
    @Nullable
    public Object evaluate(@NotNull PropertyMacroContext ctx) throws GenerationFailureException {
      switch (methodKey) {
        case 0:
          return QueriesGenerated.propertyMacro_GetValue_5_0(ctx);
        case 1:
          return QueriesGenerated.propertyMacro_GetValue_6_0(ctx);
        case 2:
          return QueriesGenerated.propertyMacro_GetValue_6_1(ctx);
        case 3:
          return QueriesGenerated.propertyMacro_GetValue_6_2(ctx);
        case 4:
          return QueriesGenerated.propertyMacro_GetValue_6_3(ctx);
        case 5:
          return QueriesGenerated.propertyMacro_GetValue_7_0(ctx);
        case 6:
          return QueriesGenerated.propertyMacro_GetValue_8_0(ctx);
        case 7:
          return QueriesGenerated.propertyMacro_GetValue_8_1(ctx);
        case 8:
          return QueriesGenerated.propertyMacro_GetValue_8_2(ctx);
        case 9:
          return QueriesGenerated.propertyMacro_GetValue_8_3(ctx);
        case 10:
          return QueriesGenerated.propertyMacro_GetValue_8_4(ctx);
        case 11:
          return QueriesGenerated.propertyMacro_GetValue_13_0(ctx);
        case 12:
          return QueriesGenerated.propertyMacro_GetValue_13_1(ctx);
        case 13:
          return QueriesGenerated.propertyMacro_GetValue_13_2(ctx);
        case 14:
          return QueriesGenerated.propertyMacro_GetValue_13_3(ctx);
        case 15:
          return QueriesGenerated.propertyMacro_GetValue_13_4(ctx);
        case 16:
          return QueriesGenerated.propertyMacro_GetValue_13_5(ctx);
        case 17:
          return QueriesGenerated.propertyMacro_GetValue_13_6(ctx);
        case 18:
          return QueriesGenerated.propertyMacro_GetValue_13_7(ctx);
        case 19:
          return QueriesGenerated.propertyMacro_GetValue_13_8(ctx);
        case 20:
          return QueriesGenerated.propertyMacro_GetValue_16_0(ctx);
        case 21:
          return QueriesGenerated.propertyMacro_GetValue_16_1(ctx);
        default:
          throw new GenerationFailureException(String.format("Inconsistent QueriesGenerated: there's no method for query %s (key: #%d)", ctx.getTemplateReference(), methodKey));
      }
    }
  }
  private final Map<String, IfMacroCondition> imcMethods = new HashMap<String, IfMacroCondition>();
  {
    int i = 0;
    imcMethods.put("1949222934982178617", new IfMC(i++));
    imcMethods.put("1949222934982669701", new IfMC(i++));
    imcMethods.put("1949222934982668952", new IfMC(i++));
    imcMethods.put("1949222934982668202", new IfMC(i++));
    imcMethods.put("8716610941203990448", new IfMC(i++));
    imcMethods.put("8642609567144377095", new IfMC(i++));
    imcMethods.put("6280652366639062033", new IfMC(i++));
    imcMethods.put("1678856199549366595", new IfMC(i++));
    imcMethods.put("6280652366639031358", new IfMC(i++));
  }
  @NotNull
  @Override
  public IfMacroCondition getIfMacroCondition(@NotNull QueryKey identity) {
    final String id = identity.getTemplateNode().getNodeId().toString();
    if (!(imcMethods.containsKey(id))) {
      return super.getIfMacroCondition(identity);
    }
    return imcMethods.get(id);
  }
  private static class IfMC implements IfMacroCondition {
    private final int methodKey;
    public IfMC(int methodKey) {
      this.methodKey = methodKey;
    }
    @Override
    public boolean check(@NotNull IfMacroContext ctx) throws GenerationFailureException {
      switch (methodKey) {
        case 0:
          return QueriesGenerated.ifMacro_Condition_6_0(ctx);
        case 1:
          return QueriesGenerated.ifMacro_Condition_7_0(ctx);
        case 2:
          return QueriesGenerated.ifMacro_Condition_7_1(ctx);
        case 3:
          return QueriesGenerated.ifMacro_Condition_7_2(ctx);
        case 4:
          return QueriesGenerated.ifMacro_Condition_9_0(ctx);
        case 5:
          return QueriesGenerated.ifMacro_Condition_13_0(ctx);
        case 6:
          return QueriesGenerated.ifMacro_Condition_16_0(ctx);
        case 7:
          return QueriesGenerated.ifMacro_Condition_16_1(ctx);
        case 8:
          return QueriesGenerated.ifMacro_Condition_16_2(ctx);
        default:
          throw new GenerationFailureException(String.format("Inconsistent QueriesGenerated: there's no condition method for if macro %s (key: #%d)", ctx.getTemplateReference(), methodKey));
      }
    }
  }
  private final Map<String, ReferenceTargetQuery> rtqMethods = new HashMap<String, ReferenceTargetQuery>();
  {
    rtqMethods.put("6280652366637908300", new RTQ(0, "p"));
    rtqMethods.put("6280652366637908340", new RTQ(1, "getVar"));
    rtqMethods.put("6280652366637911462", new RTQ(2, "string"));
    rtqMethods.put("6280652366639617780", new RTQ(3, "p"));
    rtqMethods.put("6280652366639617820", new RTQ(4, "getVar"));
    rtqMethods.put("6280652366639956035", new RTQ(5, "p"));
    rtqMethods.put("6280652366639956075", new RTQ(6, "getVar"));
    rtqMethods.put("1949222934982668941", new RTQ(7, "myTopMatcher"));
    rtqMethods.put("7197495090345735902", new RTQ(8, "propertyValue"));
    rtqMethods.put("1949222934982502678", new RTQ(9, "patternNode"));
    rtqMethods.put("1949222934982466766", new RTQ(10, "disjunct"));
    rtqMethods.put("2595803291919328504", new RTQ(11, "myVar"));
    rtqMethods.put("1678856199538903670", new RTQ(12, "myVar"));
    rtqMethods.put("5756354288101156694", new RTQ(13, "builder"));
    rtqMethods.put("2595803291919259582", new RTQ(14, "varField"));
    rtqMethods.put("1678856199538870975", new RTQ(15, "builder"));
    rtqMethods.put("1678856199538871000", new RTQ(16, "varField"));
    rtqMethods.put("1678856199539215546", new RTQ(17, "builder"));
    rtqMethods.put("1678856199539215566", new RTQ(18, "varField"));
    rtqMethods.put("1678856199540475989", new RTQ(19, "varField"));
    rtqMethods.put("6280652366638821172", new RTQ(20, "p"));
    rtqMethods.put("6280652366638820293", new RTQ(21, "p"));
    rtqMethods.put("2793477601721455528", new RTQ(22, "GeneratedPattern"));
    rtqMethods.put("2793477601720750051", new RTQ(23, "GeneratedPattern"));
    rtqMethods.put("8950533135209409920", new RTQ(24, "GeneratedPattern"));
    rtqMethods.put("8950533135209422013", new RTQ(25, "GeneratedPattern"));
  }
  @NotNull
  @Override
  public ReferenceTargetQuery getReferenceTargetQuery(@NotNull QueryKey queryKey) {
    final String id = queryKey.getTemplateNode().getNodeId().toString();
    if (!(rtqMethods.containsKey(id))) {
      return super.getReferenceTargetQuery(queryKey);
    }
    return rtqMethods.get(id);
  }
  private static class RTQ extends ReferenceTargetQuery.Base {
    private final int methodKey;
    /*package*/ RTQ(int methodKey, String templateValue) {
      super(templateValue);
      this.methodKey = methodKey;
    }
    @Nullable
    public Object evaluate(@NotNull ReferenceMacroContext ctx) throws GenerationFailureException {
      switch (methodKey) {
        case 0:
          return QueriesGenerated.referenceMacro_GetReferent_0_0(ctx);
        case 1:
          return QueriesGenerated.referenceMacro_GetReferent_0_1(ctx);
        case 2:
          return QueriesGenerated.referenceMacro_GetReferent_0_2(ctx);
        case 3:
          return QueriesGenerated.referenceMacro_GetReferent_0_3(ctx);
        case 4:
          return QueriesGenerated.referenceMacro_GetReferent_0_4(ctx);
        case 5:
          return QueriesGenerated.referenceMacro_GetReferent_0_5(ctx);
        case 6:
          return QueriesGenerated.referenceMacro_GetReferent_0_6(ctx);
        case 7:
          return QueriesGenerated.referenceMacro_GetReferent_7_0(ctx);
        case 8:
          return QueriesGenerated.referenceMacro_GetReferent_8_0(ctx);
        case 9:
          return QueriesGenerated.referenceMacro_GetReferent_9_0(ctx);
        case 10:
          return QueriesGenerated.referenceMacro_GetReferent_9_1(ctx);
        case 11:
          return QueriesGenerated.referenceMacro_GetReferent_13_0(ctx);
        case 12:
          return QueriesGenerated.referenceMacro_GetReferent_13_1(ctx);
        case 13:
          return QueriesGenerated.referenceMacro_GetReferent_14_0(ctx);
        case 14:
          return QueriesGenerated.referenceMacro_GetReferent_14_1(ctx);
        case 15:
          return QueriesGenerated.referenceMacro_GetReferent_14_2(ctx);
        case 16:
          return QueriesGenerated.referenceMacro_GetReferent_14_3(ctx);
        case 17:
          return QueriesGenerated.referenceMacro_GetReferent_14_4(ctx);
        case 18:
          return QueriesGenerated.referenceMacro_GetReferent_14_5(ctx);
        case 19:
          return QueriesGenerated.referenceMacro_GetReferent_15_0(ctx);
        case 20:
          return QueriesGenerated.referenceMacro_GetReferent_16_0(ctx);
        case 21:
          return QueriesGenerated.referenceMacro_GetReferent_16_1(ctx);
        case 22:
          return QueriesGenerated.referenceMacro_GetReferent_17_0(ctx);
        case 23:
          return QueriesGenerated.referenceMacro_GetReferent_17_1(ctx);
        case 24:
          return QueriesGenerated.referenceMacro_GetReferent_18_0(ctx);
        case 25:
          return QueriesGenerated.referenceMacro_GetReferent_18_1(ctx);
        default:
          throw new GenerationFailureException(String.format("Inconsistent QueriesGenerated: there's no method for query %s (key: #%d)", ctx.getTemplateReference(), methodKey));
      }
    }
  }
  private final Map<String, VariableValueQuery> vvqMethods = new HashMap<String, VariableValueQuery>();
  {
    vvqMethods.put("2409421742521904393", new VVQ(0));
    vvqMethods.put("2409421742521904398", new VVQ(1));
    vvqMethods.put("2409421742521904402", new VVQ(2));
  }
  @NotNull
  @Override
  public VariableValueQuery getVariableValueQuery(@NotNull QueryKey queryKey) {
    final String id = queryKey.getTemplateNode().getNodeId().toString();
    if (!(vvqMethods.containsKey(id))) {
      return super.getVariableValueQuery(queryKey);
    }
    return vvqMethods.get(id);
  }
  private static class VVQ implements VariableValueQuery {
    private final int methodKey;
    /*package*/ VVQ(int methodKey) {
      this.methodKey = methodKey;
    }
    @Nullable
    public Object evaluate(@NotNull TemplateVarContext ctx) throws GenerationFailureException {
      switch (methodKey) {
        case 0:
          return QueriesGenerated.varMacro_Value_6_0(ctx);
        case 1:
          return QueriesGenerated.varMacro_Value_8_0(ctx);
        case 2:
          return QueriesGenerated.varMacro_Value_10_0(ctx);
        default:
          throw new GenerationFailureException(String.format("Inconsistent QueriesGenerated: there's no method for query %s (key: #%d)", ctx.getTemplateReference(), methodKey));
      }
    }
  }
  private final Map<String, CallArgumentQuery> caqMethods = new HashMap<String, CallArgumentQuery>();
  {
    caqMethods.put("8642609567145868982", new CAQ(0));
    caqMethods.put("3741790230811387575", new CAQ(1));
    caqMethods.put("1949222934982538480", new CAQ(2));
    caqMethods.put("1949222934982457277", new CAQ(3));
    caqMethods.put("2793477601721750180", new CAQ(4));
    caqMethods.put("8642609567145941858", new CAQ(5));
  }
  @NotNull
  @Override
  public CallArgumentQuery getTemplateCallArgumentQuery(@NotNull QueryKey queryKey) {
    final String id = queryKey.getTemplateNode().getNodeId().toString();
    if (!(caqMethods.containsKey(id))) {
      return super.getTemplateCallArgumentQuery(queryKey);
    }
    return caqMethods.get(id);
  }
  private static class CAQ implements CallArgumentQuery {
    private final int methodKey;
    /*package*/ CAQ(int methodKey) {
      this.methodKey = methodKey;
    }
    @Nullable
    public Object evaluate(@NotNull TemplateArgumentContext ctx) throws GenerationFailureException {
      switch (methodKey) {
        case 0:
          return QueriesGenerated.templateArgumentQuery_13_0(ctx);
        case 1:
          return QueriesGenerated.templateArgumentQuery_0_0(ctx);
        case 2:
          return QueriesGenerated.templateArgumentQuery_8_0(ctx);
        case 3:
          return QueriesGenerated.templateArgumentQuery_9_0(ctx);
        case 4:
          return QueriesGenerated.templateArgumentQuery_17_0(ctx);
        case 5:
          return QueriesGenerated.templateArgumentQuery_13_1(ctx);
        default:
          throw new GenerationFailureException(String.format("Inconsistent QueriesGenerated: there's no method for query %s (key: #%d)", ctx.getTemplateReference(), methodKey));
      }
    }
  }

  private static final class CONCEPTS {
    /*package*/ static final SConcept Quotation$UL = MetaAdapterFactory.getConcept(0x3a13115c633c4c5cL, 0xbbcc75c4219e9555L, 0x1168c104659L, "jetbrains.mps.lang.quotation.structure.Quotation");
    /*package*/ static final SConcept PatternSwitchCase$Mi = MetaAdapterFactory.getConcept(0xd4615e3bd6714ba9L, 0xaf012b78369b0ba7L, 0x174c7ed18a9a3416L, "jetbrains.mps.lang.pattern.structure.PatternSwitchCase");
    /*package*/ static final SConcept PatternVariableProperty$JI = MetaAdapterFactory.getConcept(0xd4615e3bd6714ba9L, 0xaf012b78369b0ba7L, 0x60f18f425c769962L, "jetbrains.mps.lang.pattern.structure.PatternVariableProperty");
    /*package*/ static final SConcept NodeBuilderInitLink$Xj = MetaAdapterFactory.getConcept(0x3a13115c633c4c5cL, 0xbbcc75c4219e9555L, 0x4bb51009d20c8e1aL, "jetbrains.mps.lang.quotation.structure.NodeBuilderInitLink");
    /*package*/ static final SConcept PatternVariableNode$dP = MetaAdapterFactory.getConcept(0xd4615e3bd6714ba9L, 0xaf012b78369b0ba7L, 0x24062557419efb70L, "jetbrains.mps.lang.pattern.structure.PatternVariableNode");
    /*package*/ static final SConcept OrPattern$zL = MetaAdapterFactory.getConcept(0xd4615e3bd6714ba9L, 0xaf012b78369b0ba7L, 0x27f758f8bc6aaa84L, "jetbrains.mps.lang.pattern.structure.OrPattern");
    /*package*/ static final SConcept PatternBuilder$Pa = MetaAdapterFactory.getConcept(0xd4615e3bd6714ba9L, 0xaf012b78369b0ba7L, 0x240625574192fa19L, "jetbrains.mps.lang.pattern.structure.PatternBuilder");
    /*package*/ static final SInterfaceConcept AbstractAntiquotation$Tk = MetaAdapterFactory.getInterfaceConcept(0x3a13115c633c4c5cL, 0xbbcc75c4219e9555L, 0x1168c104656L, "jetbrains.mps.lang.quotation.structure.AbstractAntiquotation");
    /*package*/ static final SInterfaceConcept IMethodLike$kl = MetaAdapterFactory.getInterfaceConcept(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0x1208f458d37L, "jetbrains.mps.baseLanguage.structure.IMethodLike");
    /*package*/ static final SConcept OrPatternClause$W4 = MetaAdapterFactory.getConcept(0xd4615e3bd6714ba9L, 0xaf012b78369b0ba7L, 0x4363a36537b0b250L, "jetbrains.mps.lang.pattern.structure.OrPatternClause");
    /*package*/ static final SConcept ActionAsPattern$TP = MetaAdapterFactory.getConcept(0xd4615e3bd6714ba9L, 0xaf012b78369b0ba7L, 0x3d3ef1fc1814cb54L, "jetbrains.mps.lang.pattern.structure.ActionAsPattern");
    /*package*/ static final SConcept NodeBuilderRef$az = MetaAdapterFactory.getConcept(0x3a13115c633c4c5cL, 0xbbcc75c4219e9555L, 0x718e3f4cb7a0fa93L, "jetbrains.mps.lang.quotation.structure.NodeBuilderRef");
    /*package*/ static final SConcept PropertyId$Ig = MetaAdapterFactory.getConcept(0x7866978ea0f04cc7L, 0x81bc4d213d9375e1L, 0x5fea1eb9fefc235cL, "jetbrains.mps.lang.smodel.structure.PropertyId");
    /*package*/ static final SConcept ReferenceLinkId$Ic = MetaAdapterFactory.getConcept(0x7866978ea0f04cc7L, 0x81bc4d213d9375e1L, 0x74cb131f5923b6ecL, "jetbrains.mps.lang.smodel.structure.ReferenceLinkId");
    /*package*/ static final SConcept NodeBuilderNode$RN = MetaAdapterFactory.getConcept(0x3a13115c633c4c5cL, 0xbbcc75c4219e9555L, 0x4bb51009d20a4aa0L, "jetbrains.mps.lang.quotation.structure.NodeBuilderNode");
    /*package*/ static final SConcept Classifier$hJ = MetaAdapterFactory.getConcept(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0x101d9d3ca30L, "jetbrains.mps.baseLanguage.structure.Classifier");
    /*package*/ static final SConcept Pattern$Ke = MetaAdapterFactory.getConcept(0xd4615e3bd6714ba9L, 0xaf012b78369b0ba7L, 0x108a9cb478fL, "jetbrains.mps.lang.pattern.structure.Pattern");
    /*package*/ static final SConcept PropertyPatternVariableDeclaration$Xj = MetaAdapterFactory.getConcept(0xd4615e3bd6714ba9L, 0xaf012b78369b0ba7L, 0x108a9cb4795L, "jetbrains.mps.lang.pattern.structure.PropertyPatternVariableDeclaration");
    /*package*/ static final SConcept LinkPatternVariableDeclaration$UB = MetaAdapterFactory.getConcept(0xd4615e3bd6714ba9L, 0xaf012b78369b0ba7L, 0x108d36d955aL, "jetbrains.mps.lang.pattern.structure.LinkPatternVariableDeclaration");
    /*package*/ static final SConcept OrPatternVariableReference$At = MetaAdapterFactory.getConcept(0xd4615e3bd6714ba9L, 0xaf012b78369b0ba7L, 0x3b2f5e7b070d317cL, "jetbrains.mps.lang.pattern.structure.OrPatternVariableReference");
  }

  private static final class LINKS {
    /*package*/ static final SContainmentLink case$nt1N = MetaAdapterFactory.getContainmentLink(0xd4615e3bd6714ba9L, 0xaf012b78369b0ba7L, 0x174c7ed18a995b51L, 0x527e98a73771f431L, "case");
    /*package*/ static final SReferenceLink declaration$GelY = MetaAdapterFactory.getReferenceLink(0xd4615e3bd6714ba9L, 0xaf012b78369b0ba7L, 0x26c46d140aa61085L, 0x26c46d140aa61088L, "declaration");
    /*package*/ static final SReferenceLink link$ckAZ = MetaAdapterFactory.getReferenceLink(0x3a13115c633c4c5cL, 0xbbcc75c4219e9555L, 0x4bb51009d20c8e1aL, 0x4bb51009d20c8e1cL, "link");
    /*package*/ static final SContainmentLink initValue$UJfh = MetaAdapterFactory.getContainmentLink(0x3a13115c633c4c5cL, 0xbbcc75c4219e9555L, 0x4bb51009d20c8e1aL, 0x16240b8e9e79db03L, "initValue");
    /*package*/ static final SReferenceLink variable$w5gw = MetaAdapterFactory.getReferenceLink(0xd4615e3bd6714ba9L, 0xaf012b78369b0ba7L, 0x2b7df577ffbb6a85L, 0x2b7df577ffbb6a86L, "variable");
    /*package*/ static final SContainmentLink pattern$fJGl = MetaAdapterFactory.getContainmentLink(0xd4615e3bd6714ba9L, 0xaf012b78369b0ba7L, 0x108a9cb4791L, 0x7d8b4408504314cdL, "pattern");
    /*package*/ static final SContainmentLink quotedNode$kInw = MetaAdapterFactory.getContainmentLink(0x3a13115c633c4c5cL, 0xbbcc75c4219e9555L, 0x1168c104659L, 0x1168c10465aL, "quotedNode");
    /*package*/ static final SReferenceLink declaration$qXxw = MetaAdapterFactory.getReferenceLink(0xd4615e3bd6714ba9L, 0xaf012b78369b0ba7L, 0x3b2f5e7b070d317cL, 0x3b2f5e7b070d317dL, "declaration");
    /*package*/ static final SContainmentLink pattern$LFiH = MetaAdapterFactory.getContainmentLink(0xd4615e3bd6714ba9L, 0xaf012b78369b0ba7L, 0x174c7ed18a9a3416L, 0x174c7ed18b16ecf4L, "pattern");
    /*package*/ static final SReferenceLink declaration$6hl0 = MetaAdapterFactory.getReferenceLink(0xd4615e3bd6714ba9L, 0xaf012b78369b0ba7L, 0x174c7ed18b16ecfcL, 0x174c7ed18b16ecfdL, "declaration");
    /*package*/ static final SContainmentLink pattern$m3eu = MetaAdapterFactory.getContainmentLink(0xd4615e3bd6714ba9L, 0xaf012b78369b0ba7L, 0x50f8d1ebd50bbeb0L, 0x50f8d1ebd50bbeb3L, "pattern");
    /*package*/ static final SContainmentLink pattern$65eZ = MetaAdapterFactory.getContainmentLink(0xd4615e3bd6714ba9L, 0xaf012b78369b0ba7L, 0x7c36ae76ea76f63bL, 0x7c36ae76ea76f63dL, "pattern");
    /*package*/ static final SContainmentLink builder$Ubq1 = MetaAdapterFactory.getContainmentLink(0xd4615e3bd6714ba9L, 0xaf012b78369b0ba7L, 0x240625574192fa19L, 0x2406255741930411L, "builder");
    /*package*/ static final SReferenceLink property$NCMw = MetaAdapterFactory.getReferenceLink(0x3a13115c633c4c5cL, 0xbbcc75c4219e9555L, 0x4bb51009d20b0325L, 0x4bb51009d20b0326L, "property");
    /*package*/ static final SContainmentLink expression$nt1k = MetaAdapterFactory.getContainmentLink(0xd4615e3bd6714ba9L, 0xaf012b78369b0ba7L, 0x174c7ed18a995b51L, 0x527e98a73771f430L, "expression");
    /*package*/ static final SContainmentLink body$6jgq = MetaAdapterFactory.getContainmentLink(0xd4615e3bd6714ba9L, 0xaf012b78369b0ba7L, 0x174c7ed18a9a3416L, 0x10ef02d8048L, "body");
    /*package*/ static final SContainmentLink defaultBlock$twKh = MetaAdapterFactory.getContainmentLink(0xd4615e3bd6714ba9L, 0xaf012b78369b0ba7L, 0x174c7ed18a995b51L, 0x53cfca750aa0c6d0L, "defaultBlock");
    /*package*/ static final SContainmentLink clause$j$BB = MetaAdapterFactory.getContainmentLink(0xd4615e3bd6714ba9L, 0xaf012b78369b0ba7L, 0x27f758f8bc6aaa84L, 0x27f758f8bc6acaceL, "clause");
    /*package*/ static final SContainmentLink action$dtRs = MetaAdapterFactory.getContainmentLink(0xd4615e3bd6714ba9L, 0xaf012b78369b0ba7L, 0x3d3ef1fc1814cb54L, 0x3d3ef1fc1814cb59L, "action");
    /*package*/ static final SContainmentLink expression$JCaZ = MetaAdapterFactory.getContainmentLink(0x3a13115c633c4c5cL, 0xbbcc75c4219e9555L, 0x718e3f4cb7a3132eL, 0x718e3f4cb7a31330L, "expression");
    /*package*/ static final SContainmentLink smodelAttribute$K8bJ = MetaAdapterFactory.getContainmentLink(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x10802efe25aL, 0x47bf8397520e5942L, "smodelAttribute");
    /*package*/ static final SContainmentLink initValue$nhHN = MetaAdapterFactory.getContainmentLink(0x3a13115c633c4c5cL, 0xbbcc75c4219e9555L, 0x4bb51009d20b0325L, 0x16240b8e9e79d891L, "initValue");
    /*package*/ static final SContainmentLink values$oju9 = MetaAdapterFactory.getContainmentLink(0x3a13115c633c4c5cL, 0xbbcc75c4219e9555L, 0x4bb51009d20a4aa0L, 0x4bb51009d20b033bL, "values");
    /*package*/ static final SContainmentLink statement$WHn8 = MetaAdapterFactory.getContainmentLink(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf8cc56b200L, 0xf8cc6bf961L, "statement");
  }

  private static final class PROPS {
    /*package*/ static final SProperty metaClass$tHD7 = MetaAdapterFactory.getProperty(0xc72da2b97cce4447L, 0x8389f407dc1158b7L, 0xf979bd086aL, 0xf980556927L, "metaClass");
    /*package*/ static final SProperty varName$DO_b = MetaAdapterFactory.getProperty(0xd4615e3bd6714ba9L, 0xaf012b78369b0ba7L, 0x108a9cb4793L, 0x108a9cb4794L, "varName");
    /*package*/ static final SProperty varName$DOAw = MetaAdapterFactory.getProperty(0xd4615e3bd6714ba9L, 0xaf012b78369b0ba7L, 0x108a9cb4795L, 0x108a9cb4796L, "varName");
    /*package*/ static final SProperty varName$Oh7T = MetaAdapterFactory.getProperty(0xd4615e3bd6714ba9L, 0xaf012b78369b0ba7L, 0x108d36d955aL, 0x108d36e0ea4L, "varName");
    /*package*/ static final SProperty name$tAp1 = MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name");
    /*package*/ static final SProperty stringValueMigrated$gFe8 = MetaAdapterFactory.getProperty(0x3a13115c633c4c5cL, 0xbbcc75c4219e9555L, 0x384b195d1ed21709L, 0x1e2950a3c41b89ecL, "stringValueMigrated");
  }
}
