package jetbrains.mps.lang.test.runtime;

/*Generated by MPS */

import jetbrains.mps.tool.environment.Environment;
import jetbrains.mps.project.Project;
import org.jetbrains.mps.openapi.model.SModel;
import org.jetbrains.mps.openapi.model.SNode;
import org.jetbrains.mps.openapi.model.SNodeId;
import org.jetbrains.mps.openapi.persistence.PersistenceFacade;
import java.util.concurrent.atomic.AtomicReference;
import jetbrains.mps.ide.ThreadUtils;
import java.util.Map;
import java.util.HashMap;
import jetbrains.mps.smodel.CopyUtil;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.internal.collections.runtime.IVisitor;
import java.util.ArrayList;
import org.jetbrains.mps.openapi.language.SConcept;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;

public class ProjectTestHelper {

  private TestParametersCache myParametersCache;
  private Environment myEnvironment;

  public ProjectTestHelper(String projectPath, String modelRef) {
    myParametersCache = new TestParametersCache(ProjectTestHelper.class, projectPath, modelRef, false);
  }

  public void setEnvironment(Environment environment) throws Exception {
    this.myEnvironment = environment;
    myParametersCache.initializeOnce(this, myEnvironment);
  }

  public void dispose() {
    myParametersCache.clean();
  }

  public Project project() {
    return myParametersCache.getProject();
  }

  public SModel model() {
    return myParametersCache.getTransientModel();
  }

  /**
   * Must be invoked from read action.
   */
  public SNode lookupNode(String nodeId) {
    SNodeId snid = PersistenceFacade.getInstance().createNodeId(nodeId);
    return model().getNode(snid);
  }

  public void asCommand(final Testable testable) throws Exception {
    final AtomicReference<Exception> testableEx = new AtomicReference<Exception>();
    Exception loggedEx = ThreadUtils.runInUIThreadAndWait(() -> project().getModelAccess().executeCommand(() -> {
      try {
        testable.test();
      } catch (Exception e) {
        testableEx.set(e);
      }
    }));
    Exception ex = testableEx.get();
    if (loggedEx != null) {
      if (ex != null) {
        ex.addSuppressed(loggedEx);
      } else {
        ex = loggedEx;
      }
    }
    if (ex != null) {
      throw ex;
    }
  }

  public void asRead(final Testable testable) throws Exception {
    final AtomicReference<Exception> testableEx = new AtomicReference<Exception>();
    project().getModelAccess().runReadAction(() -> {
      try {
        testable.test();
      } catch (Exception e) {
        testableEx.set(e);
      }
    });
    if (testableEx.get() != null) {
      throw testableEx.get();
    }
  }

  public TestCase testCase() {
    return new TestCase(this);
  }

  public static class TestCase implements Fixture {
    private Map<SNode, SNode> copiedRoots = new HashMap<>();
    private final ProjectTestHelper helper;

    public TestCase(ProjectTestHelper helper) {
      this.helper = helper;
    }

    @Override
    public SModel model() {
      return helper.model();
    }

    @Override
    public SNode copied(String id) {
      return copiedRoots.get(helper.lookupNode(id));
    }

    @Override
    public SNode original(String id) {
      return helper.lookupNode(id);
    }

    public TestCase withCopyOf(final String nodeId) throws Exception {
      helper.asCommand(() -> {
        SNode orig = helper.lookupNode(nodeId);
        SNode copy = CopyUtil.copy(orig, copiedRoots, true);
        ListSequence.fromList(SNodeOperations.getNodeDescendants(copy, CONCEPTS.AbstractTestNodeAnnotation$lh, false, new SAbstractConcept[]{})).toListSequence().visitAll(new IVisitor<SNode>() {
          public void visit(SNode it) {
            SNodeOperations.deleteNode(it);
          }
        });
        model().addRootNode(copy);
      });
      return this;
    }

    public TestCase command(Testable testable) throws Exception {
      helper.asCommand(testable);
      return this;
    }

    public TestCase command(final FixtureTestable testable) throws Exception {
      helper.asCommand(() -> testable.test(TestCase.this));
      return this;
    }

    public TestCase read(Testable testable) throws Exception {
      helper.asRead(testable);
      return this;
    }

    public TestCase read(final FixtureTestable testable) throws Exception {
      helper.asRead(() -> testable.test(TestCase.this));
      return this;
    }

    public void done() throws Exception {
      helper.asCommand(() -> {
        ListSequence.fromList(ListSequence.fromListWithValues(new ArrayList<SNode>(), copiedRoots.values())).visitAll(new IVisitor<SNode>() {
          public void visit(SNode it) {
            SNodeOperations.deleteNode(it);
          }
        });
        copiedRoots.clear();
      });
    }
  }

  private static final class CONCEPTS {
    /*package*/ static final SConcept AbstractTestNodeAnnotation$lh = MetaAdapterFactory.getConcept(0x8585453e6bfb4d80L, 0x98deb16074f1d86cL, 0x11e0d52da47L, "jetbrains.mps.lang.test.structure.AbstractTestNodeAnnotation");
  }
}
