package jetbrains.mps.lang.generator.generationContext.migration;

/*Generated by MPS */

import jetbrains.mps.lang.migration.runtime.base.MigrationScriptBase;
import org.jetbrains.mps.openapi.model.SNode;
import org.jetbrains.mps.openapi.module.SModule;
import org.jetbrains.mps.openapi.module.SearchScope;
import jetbrains.mps.lang.smodel.query.runtime.CommandUtil;
import jetbrains.mps.project.EditableFilteringScope;
import jetbrains.mps.lang.smodel.query.runtime.QueryExecutionContext;
import jetbrains.mps.lang.pattern.migration.PropertyPatternVariableMigration;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import jetbrains.mps.baseLanguage.behavior.IOperation__BehaviorDescriptor;
import jetbrains.mps.lang.migration.runtime.base.MigrationScriptReference;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import java.util.ArrayList;

public class MigratePropertyPatternVariables extends MigrationScriptBase {
  public String getCaption() {
    return "Migrate property pattern variables (gencontext)";
  }
  @Override
  public boolean isRerunnable() {
    return true;
  }
  public SNode execute(final SModule m) {
    doExecute(m);
    return null;
  }
  public void doExecute(final SModule m) {
    {
      SearchScope scope_mymgc3_a0d = CommandUtil.createScope(m);
      final SearchScope scope_mymgc3_a0d_0 = new EditableFilteringScope(scope_mymgc3_a0d);
      QueryExecutionContext context = new QueryExecutionContext() {
        public SearchScope getDefaultSearchScope() {
          return scope_mymgc3_a0d_0;
        }
      };
      new PropertyPatternVariableMigration<SNode>() {
        @Override
        protected Iterable<SNode> getUsagesToMigrate() {
          return CommandUtil.instances(CommandUtil.selectScope(null, context), MetaAdapterFactory.getConcept(0xd7706f639be2479cL, 0xa3daae92af1e64d5L, 0x186874d40ed9c758L, "jetbrains.mps.lang.generator.generationContext.structure.GenerationContextOp_PropertyPatternRef"), false);
        }
        @Override
        protected SNode getDeclaration(SNode usage) {
          return SLinkOperations.getTarget(usage, MetaAdapterFactory.getReferenceLink(0xd7706f639be2479cL, 0xa3daae92af1e64d5L, 0x186874d40ed9c758L, 0x186874d40ed9c75cL, "propertyPatternVar"));
        }
        @Override
        protected void migrateRawValue(SNode usage, SNode datatype) {
          downgradeRawValueType(IOperation__BehaviorDescriptor.getDotExpression_idhO_4GYO.invoke(usage), datatype);
        }
        @Override
        protected void migrateEnumValue(SNode usage, SNode enumeration) {
          downgradeEnumType(IOperation__BehaviorDescriptor.getDotExpression_idhO_4GYO.invoke(usage), enumeration);
        }
      }.migrate();
    }
  }
  public Iterable<MigrationScriptReference> executeAfter() {
    return ListSequence.fromListAndArray(new ArrayList<MigrationScriptReference>(), new MigrationScriptReference(MetaAdapterFactory.getLanguage(0xc72da2b97cce4447L, 0x8389f407dc1158b7L, "jetbrains.mps.lang.structure"), 8));
  }
  public MigrationScriptReference getDescriptor() {
    return new MigrationScriptReference(MetaAdapterFactory.getLanguage(0xd7706f639be2479cL, 0xa3daae92af1e64d5L, "jetbrains.mps.lang.generator.generationContext"), 1);
  }

}
