package jetbrains.mps.java.platform.highlighters;

/*Generated by MPS */

import jetbrains.mps.annotations.GeneratedClass;
import jetbrains.mps.nodeEditor.DefaultEditorMessage;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.openapi.editor.message.EditorMessageOwner;
import java.awt.Color;
import java.awt.Graphics;
import jetbrains.mps.nodeEditor.EditorComponent;
import jetbrains.mps.openapi.editor.cells.EditorCell;

@GeneratedClass(node = "r:fa4569a3-1bd4-4159-97bc-db03b3aeff88(jetbrains.mps.java.platform.highlighters)/5916754392152656888", model = "r:fa4569a3-1bd4-4159-97bc-db03b3aeff88(jetbrains.mps.java.platform.highlighters)")
public class ToDoMessage extends DefaultEditorMessage {
  public ToDoMessage(SNode node, String message, EditorMessageOwner owner) {
    super(node, Color.BLUE, message, owner);
  }
  @Override
  public void paint(Graphics graphics, EditorComponent component, EditorCell cell) {
  }
}
