package jetbrains.mps.baseLanguage.math.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.EnumerationDescriptorBase;
import jetbrains.mps.smodel.adapter.ids.PrimitiveTypeId;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import jetbrains.mps.lang.smodel.EnumerationLiteralsIndex;
import java.util.List;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.annotations.NotNull;

public class EnumerationDescriptor_RoundingMode extends EnumerationDescriptorBase {

  public EnumerationDescriptor_RoundingMode() {
    super(0x3304fc6e7c6b401eL, 0xa016b944934bb21fL, 0x120568e25cfL, "RoundingMode", "r:cb1a36c8-1ffb-415a-aba8-afb9dc042d1b(jetbrains.mps.baseLanguage.math.structure)/4241665505353448440", PrimitiveTypeId.INTEGER);
  }

  private final EnumerationDescriptor.MemberDescriptor myMember_CEILING_0 = new EnumerationDescriptor.MemberDescriptor("CEILING", "CEILING", 0x120568e25d0L, "r:cb1a36c8-1ffb-415a-aba8-afb9dc042d1b(jetbrains.mps.baseLanguage.math.structure)/4241665505353448442", "CEILING", "0");
  private final EnumerationDescriptor.MemberDescriptor myMember_DOWN_0 = new EnumerationDescriptor.MemberDescriptor("DOWN", "DOWN", 0x120568e9842L, "r:cb1a36c8-1ffb-415a-aba8-afb9dc042d1b(jetbrains.mps.baseLanguage.math.structure)/4241665505353448443", "DOWN", "1");
  private final EnumerationDescriptor.MemberDescriptor myMember_FLOOR_0 = new EnumerationDescriptor.MemberDescriptor("FLOOR", "FLOOR", 0x120568e98d0L, "r:cb1a36c8-1ffb-415a-aba8-afb9dc042d1b(jetbrains.mps.baseLanguage.math.structure)/4241665505353448444", "FLOOR", "2");
  private final EnumerationDescriptor.MemberDescriptor myMember_HALF_DOWN_0 = new EnumerationDescriptor.MemberDescriptor("HALF_DOWN", "HALF_DOWN", 0x120568e997dL, "r:cb1a36c8-1ffb-415a-aba8-afb9dc042d1b(jetbrains.mps.baseLanguage.math.structure)/4241665505353448445", "HALF_DOWN", "3");
  private final EnumerationDescriptor.MemberDescriptor myMember_HALF_EVEN_0 = new EnumerationDescriptor.MemberDescriptor("HALF_EVEN", "HALF_EVEN", 0x120568e99ebL, "r:cb1a36c8-1ffb-415a-aba8-afb9dc042d1b(jetbrains.mps.baseLanguage.math.structure)/4241665505353448446", "HALF_EVEN", "4");
  private final EnumerationDescriptor.MemberDescriptor myMember_HALF_UP_0 = new EnumerationDescriptor.MemberDescriptor("HALF_UP", "HALF_UP", 0x120568f1650L, "r:cb1a36c8-1ffb-415a-aba8-afb9dc042d1b(jetbrains.mps.baseLanguage.math.structure)/4241665505353448447", "HALF_UP", "5");
  private final EnumerationDescriptor.MemberDescriptor myMember_UNNECCESARY_0 = new EnumerationDescriptor.MemberDescriptor("UNNECCESARY", "UNNECCESARY", 0x120568f2853L, "r:cb1a36c8-1ffb-415a-aba8-afb9dc042d1b(jetbrains.mps.baseLanguage.math.structure)/4241665505353448448", "UNNECCESARY", "6");
  private final EnumerationDescriptor.MemberDescriptor myMember_UP_0 = new EnumerationDescriptor.MemberDescriptor("UP", "UP", 0x120568f3db1L, "r:cb1a36c8-1ffb-415a-aba8-afb9dc042d1b(jetbrains.mps.baseLanguage.math.structure)/4241665505353448449", "UP", "7");

  private final EnumerationLiteralsIndex myIndex = EnumerationLiteralsIndex.build(0x3304fc6e7c6b401eL, 0xa016b944934bb21fL, 0x120568e25cfL, 0x120568e25d0L, 0x120568e9842L, 0x120568e98d0L, 0x120568e997dL, 0x120568e99ebL, 0x120568f1650L, 0x120568f2853L, 0x120568f3db1L);
  private final List<EnumerationDescriptor.MemberDescriptor> myMembers = new EnumerationDescriptorBase.MembersList(myIndex, myMember_CEILING_0, myMember_DOWN_0, myMember_FLOOR_0, myMember_HALF_DOWN_0, myMember_HALF_EVEN_0, myMember_HALF_UP_0, myMember_UNNECCESARY_0, myMember_UP_0);

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getDefault() {
    return myMember_HALF_EVEN_0;
  }

  @NotNull
  @Override
  public List<EnumerationDescriptor.MemberDescriptor> getMembers() {
    return myMembers;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(@Nullable String memberName) {
    if (memberName == null) {
      return null;
    }
    switch (memberName) {
      case "CEILING":
        return myMember_CEILING_0;
      case "DOWN":
        return myMember_DOWN_0;
      case "FLOOR":
        return myMember_FLOOR_0;
      case "HALF_DOWN":
        return myMember_HALF_DOWN_0;
      case "HALF_EVEN":
        return myMember_HALF_EVEN_0;
      case "HALF_UP":
        return myMember_HALF_UP_0;
      case "UNNECCESARY":
        return myMember_UNNECCESARY_0;
      case "UP":
        return myMember_UP_0;
    }
    return null;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(long idValue) {
    int index = myIndex.index(idValue);
    if (index == -1) {
      return null;
    }
    return myMembers.get(index);
  }
}
