package jetbrains.mps.checkers;

/*Generated by MPS */

import jetbrains.mps.annotations.GeneratedClass;
import jetbrains.mps.errors.item.ReportItem;
import jetbrains.mps.baseLanguage.closures.runtime._FunctionTypes;
import org.jetbrains.mps.openapi.module.SRepository;
import org.jetbrains.mps.openapi.util.Consumer;
import org.jetbrains.mps.openapi.util.ProgressMonitor;

@GeneratedClass(node = "r:ba41e9c6-15ca-4a47-95f2-6a81c2318547(jetbrains.mps.checkers)/8195773907766032343", model = "r:ba41e9c6-15ca-4a47-95f2-6a81c2318547(jetbrains.mps.checkers)")
public class SkippingChecker<O, I extends ReportItem> implements IAbstractChecker<O, I> {
  private IAbstractChecker<O, ? extends I> myOrigin;
  private _FunctionTypes._return_P2_E0<? extends Boolean, ? super O, ? super SRepository> myAccept;
  public SkippingChecker(IAbstractChecker<O, ? extends I> origin, _FunctionTypes._return_P2_E0<? extends Boolean, ? super O, ? super SRepository> accept) {
    myOrigin = origin;
    myAccept = accept;
  }
  @Override
  public void check(O toCheck, SRepository repository, Consumer<? super I> errorCollector, ProgressMonitor monitor) {
    if (myAccept.invoke(toCheck, repository)) {
      myOrigin.check(toCheck, repository, errorCollector, monitor);
    }
  }
}
