package jetbrains.mps.baseLanguage.intentions;

/*Generated by MPS */

import jetbrains.mps.intentions.AbstractIntentionDescriptor;
import jetbrains.mps.openapi.intentions.IntentionFactory;
import jetbrains.mps.openapi.intentions.Kind;
import jetbrains.mps.smodel.SNodePointer;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.openapi.editor.EditorContext;
import java.util.Collection;
import jetbrains.mps.openapi.intentions.IntentionExecutable;
import java.util.List;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import java.util.ArrayList;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;
import jetbrains.mps.intentions.AbstractIntentionExecutable;
import jetbrains.mps.openapi.intentions.ParameterizedIntentionExecutable;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SConceptOperations;
import jetbrains.mps.smodel.action.SNodeFactoryOperations;
import jetbrains.mps.baseLanguage.actions.AlterStatementListContainerFactoryUtils;
import jetbrains.mps.openapi.intentions.IntentionDescriptor;
import org.jetbrains.mps.openapi.language.SConcept;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;

public final class AlterStatementListContainer_Intention extends AbstractIntentionDescriptor implements IntentionFactory {
  public AlterStatementListContainer_Intention() {
    super(Kind.NORMAL, false, new SNodePointer("r:00000000-0000-4000-0000-011c895902c6(jetbrains.mps.baseLanguage.intentions)", "8176191621190087466"));
  }
  @Override
  public String getPresentation() {
    return "AlterStatementListContainer";
  }
  @Override
  public boolean isApplicable(final SNode node, final EditorContext editorContext) {
    if (!(isApplicableToNode(node, editorContext))) {
      return false;
    }
    return true;
  }
  private boolean isApplicableToNode(final SNode node, final EditorContext editorContext) {
    return true;
  }
  @Override
  public boolean isSurroundWith() {
    return false;
  }
  public Collection<IntentionExecutable> instances(final SNode node, final EditorContext context) {
    List<IntentionExecutable> list = ListSequence.fromList(new ArrayList<IntentionExecutable>());
    List<SAbstractConcept> paramList = parameter(node, context);
    if (paramList != null) {
      for (SAbstractConcept param : paramList) {
        ListSequence.fromList(list).addElement(new IntentionImplementation(param));
      }
    }
    return list;
  }
  private List<SAbstractConcept> parameter(final SNode node, final EditorContext editorContext) {
    List<SAbstractConcept> list = ListSequence.fromListAndArray(new ArrayList<SAbstractConcept>(), AUX_vvwez.IfStatement_9dbf9b10, AUX_vvwez.WhileStatement_1f5f4332, AUX_vvwez.DoWhileStatement_50b6f79b, AUX_vvwez.ForStatement_1eab9ef9, AUX_vvwez.ForeachStatement_bf20b0bc, AUX_vvwez.ForEachStatement_a2950921);
    ListSequence.fromList(list).removeElement(SNodeOperations.getConcept(node));
    if (SNodeOperations.isInstanceOf(node, AUX_vvwez.ForeachStatement_bf20b0bc) || SNodeOperations.isInstanceOf(node, AUX_vvwez.ForEachStatement_a2950921)) {
      ListSequence.fromList(list).removeElement(AUX_vvwez.ForeachStatement_bf20b0bc);
      ListSequence.fromList(list).removeElement(AUX_vvwez.ForEachStatement_a2950921);
    }
    return list;
  }
  /*package*/ final class IntentionImplementation extends AbstractIntentionExecutable implements ParameterizedIntentionExecutable {
    private SAbstractConcept myParameter;
    public IntentionImplementation(SAbstractConcept parameter) {
      myParameter = parameter;
    }
    @Override
    public String getDescription(final SNode node, final EditorContext editorContext) {
      String targetName;
      if (SConceptOperations.isExactly(SNodeOperations.asSConcept(myParameter), AUX_vvwez.ForEachStatement_a2950921)) {
        targetName = "'for (var in iterable)'";
      } else if (SConceptOperations.isExactly(SNodeOperations.asSConcept(myParameter), AUX_vvwez.ForeachStatement_bf20b0bc)) {
        targetName = "'for Type var: iterable)'";
      } else {
        targetName = myParameter.getConceptAlias() + ((SConceptOperations.isExactly(SNodeOperations.asSConcept(myParameter), AUX_vvwez.DoWhileStatement_50b6f79b) ? "-While" : ""));
      }
      targetName += " statement";
      targetName = "Change to " + targetName;
      return targetName;
    }
    @Override
    public void execute(final SNode node, final EditorContext editorContext) {
      SNode newInitializedInstance = SNodeFactoryOperations.createNewNode(myParameter, null);
      AlterStatementListContainerFactoryUtils.buildContainerIfPossible(node, newInitializedInstance);
      SNodeOperations.replaceWithAnother(node, newInitializedInstance);
      editorContext.selectWRTFocusPolicy(newInitializedInstance);
    }
    @Override
    public IntentionDescriptor getDescriptor() {
      return AlterStatementListContainer_Intention.this;
    }
    public Object getParameter() {
      return myParameter;
    }
  }

  private static final class AUX_vvwez {
    /*package*/ static final SConcept IfStatement_9dbf9b10 = MetaAdapterFactory.getConcept(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf8cc56b217L, "jetbrains.mps.baseLanguage.structure.IfStatement");
    /*package*/ static final SConcept WhileStatement_1f5f4332 = MetaAdapterFactory.getConcept(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xfaa4bf0f2fL, "jetbrains.mps.baseLanguage.structure.WhileStatement");
    /*package*/ static final SConcept DoWhileStatement_50b6f79b = MetaAdapterFactory.getConcept(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0x11232674988L, "jetbrains.mps.baseLanguage.structure.DoWhileStatement");
    /*package*/ static final SConcept ForStatement_1eab9ef9 = MetaAdapterFactory.getConcept(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0x10a698082feL, "jetbrains.mps.baseLanguage.structure.ForStatement");
    /*package*/ static final SConcept ForeachStatement_bf20b0bc = MetaAdapterFactory.getConcept(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0x10a6933ce33L, "jetbrains.mps.baseLanguage.structure.ForeachStatement");
    /*package*/ static final SConcept ForEachStatement_a2950921 = MetaAdapterFactory.getConcept(0x8388864671ce4f1cL, 0x9c53c54016f6ad4fL, 0x10cac65f399L, "jetbrains.mps.baseLanguage.collections.structure.ForEachStatement");
  }
}
