package jetbrains.mps.kotlin.tests.editor.transforms;

/*Generated by MPS */

import jetbrains.mps.MPSLaunch;
import jetbrains.mps.lang.test.runtime.BaseTransformationTest;
import org.junit.jupiter.api.extension.RegisterExtension;
import jetbrains.mps.lang.test.runtime.TestParametersCacheExtension;
import jetbrains.mps.lang.test.runtime.TestParametersCache;
import org.junit.jupiter.api.Test;
import jetbrains.mps.lang.test.runtime.BaseEditorTestBody;
import jetbrains.mps.lang.test.runtime.TransformationTest;

@MPSLaunch
public class NestedClassType_Nullable_Test extends BaseTransformationTest {
  @RegisterExtension
  private static final TestParametersCacheExtension ourParametersCacheExtension = new TestParametersCacheExtension(new TestParametersCache(NestedClassType_Nullable_Test.class, "${mps_home}", "r:a3e0a10d-78d6-4951-8938-42152651f9e3(jetbrains.mps.kotlin.tests.editor.transforms@tests)", false));

  public NestedClassType_Nullable_Test() {
    super(ourParametersCacheExtension.getParametersCache());
  }

  @Test
  public void test_NestedClassType_Nullable() throws Throwable {
    new TestBody(this).testMethod();
  }

  /*package*/ static class TestBody extends BaseEditorTestBody {

    /*package*/ TestBody(TransformationTest owner) {
      super(owner);
    }

    @Override
    public void testMethodImpl() throws Exception {
      initEditorComponent("4599083868788822121", "4599083868788822125");
      typeString("?");
    }
  }
}
