package jetbrains.mps.debug.api.programState;

/*Generated by MPS */

import jetbrains.mps.annotations.GeneratedClass;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.mps.openapi.model.SNodeReference;

/**
 * Provisional interface to transit existing IWatchable implementations. Please use {@link jetbrains.mps.debug.api.programState.AbstractWatchable }.
 * This interface would get merged into IWatchable in the next release
 */
@GeneratedClass(node = "r:0a0d7eec-6e5a-412b-8e16-e3ee5ed7fb95(jetbrains.mps.debug.api.programState)/6559558851652287506", model = "r:0a0d7eec-6e5a-412b-8e16-e3ee5ed7fb95(jetbrains.mps.debug.api.programState)")
public interface Watchable2 extends IWatchable {
  /**
   * 
   * @return optional node in a source model associated with this watchable object.
   */
  @Nullable
  SNodeReference getSourceNode();
}
