package jetbrains.mps.vcs.plugin;

/*Generated by MPS */

import jetbrains.mps.annotations.GeneratedClass;
import jetbrains.mps.plugins.actions.GeneratedActionGroup;
import org.jetbrains.annotations.Nullable;
import jetbrains.mps.workbench.action.ApplicationPlugin;

@GeneratedClass(node = "r:5ec7bf64-acd2-448b-8f9b-ce1b8d920038(jetbrains.mps.vcs.plugin)/7545884443035896622", model = "r:5ec7bf64-acd2-448b-8f9b-ce1b8d920038(jetbrains.mps.vcs.plugin)")
public class VCSModelActions_ActionGroup extends GeneratedActionGroup {
  public static final String ID = "jetbrains.mps.vcs.plugin.VCSModelActions_ActionGroup";

  public VCSModelActions_ActionGroup(@Nullable ApplicationPlugin plugin) {
    super("VCSModelActions", ID, plugin);
    setIsInternal(false);
    setPopup(false);
    VCSModelActions_ActionGroup.this.addAction("jetbrains.mps.vcs.plugin.ShowDifferencesWithModelOnDisk_Action");
    VCSModelActions_ActionGroup.this.addAction("jetbrains.mps.vcs.plugin.ReRunMergeFromBackup_Action");
    VCSModelActions_ActionGroup.this.addAction("jetbrains.mps.vcs.plugin.CompareTransientModels_Action");
  }
}
