package jetbrains.mps.kotlin.behavior;

/*Generated by MPS */

import jetbrains.mps.core.aspects.behaviour.BaseBHDescriptor;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import jetbrains.mps.core.aspects.behaviour.api.SMethod;
import jetbrains.mps.core.aspects.behaviour.SMethodBuilder;
import jetbrains.mps.core.aspects.behaviour.SJavaCompoundTypeImpl;
import jetbrains.mps.core.aspects.behaviour.AccessPrivileges;
import jetbrains.mps.kotlin.api.members.SignatureCollector;
import jetbrains.mps.kotlin.api.types.identifiers.TypeKey;
import org.jetbrains.mps.openapi.model.SNode;
import java.util.List;
import java.util.Arrays;
import org.jetbrains.annotations.NotNull;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;
import jetbrains.mps.kotlin.api.types.identifiers.UnmatchableType;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import jetbrains.mps.core.aspects.behaviour.api.SConstructor;
import org.jetbrains.annotations.Nullable;
import jetbrains.mps.core.aspects.behaviour.api.BHMethodNotFoundException;
import org.jetbrains.mps.openapi.language.SContainmentLink;
import org.jetbrains.mps.openapi.language.SInterfaceConcept;
import org.jetbrains.mps.openapi.language.SProperty;

public final class UnresolvedParsedReference__BehaviorDescriptor extends BaseBHDescriptor {
  private static final SAbstractConcept CONCEPT = MetaAdapterFactory.getConcept(0x6b3888c1980244d8L, 0x8baff8e6c33ed689L, 0x430acdda9dcb793eL, "jetbrains.mps.kotlin.structure.UnresolvedParsedReference");

  public static final SMethod<Void> populateTypeSignatures_id5q426iHK5S9 = new SMethodBuilder<Void>(new SJavaCompoundTypeImpl(Void.class)).name("populateSignatures").modifiers(8, AccessPrivileges.PUBLIC).concept(CONCEPT).baseMethodId(6234117012692426249L).languageId(0x8baff8e6c33ed689L, 0x6b3888c1980244d8L).build2(SMethodBuilder.createJavaParameter(SignatureCollector.class, ""));
  public static final SMethod<String> toString_id4nn3FPlZH$r = new SMethodBuilder<String>(new SJavaCompoundTypeImpl(String.class)).name("toString").modifiers(8, AccessPrivileges.PUBLIC).concept(CONCEPT).baseMethodId(5032507314964191515L).languageId(0x8baff8e6c33ed689L, 0x6b3888c1980244d8L).build2(SMethodBuilder.createJavaParameter(Boolean.TYPE, ""));
  public static final SMethod<TypeKey> typeKey_idJmO2PmZtH5 = new SMethodBuilder<TypeKey>(new SJavaCompoundTypeImpl(TypeKey.class)).name("shallowId").modifiers(8, AccessPrivileges.PUBLIC).concept(CONCEPT).baseMethodId(853098072584870725L).languageId(0x8baff8e6c33ed689L, 0x6b3888c1980244d8L).build2();
  public static final SMethod<Boolean> isResolved_id4MvRlgZCbFz = new SMethodBuilder<Boolean>(new SJavaCompoundTypeImpl(Boolean.TYPE)).name("isResolved").modifiers(8, AccessPrivileges.PUBLIC).concept(CONCEPT).baseMethodId(5521375022094007011L).languageId(0x8baff8e6c33ed689L, 0x6b3888c1980244d8L).build2();
  public static final SMethod<SNode> tryResolve_id4MvRlgZCbFB = new SMethodBuilder<SNode>(new SJavaCompoundTypeImpl((Class<SNode>) ((Class) Object.class))).name("tryResolve").modifiers(8, AccessPrivileges.PUBLIC).concept(CONCEPT).baseMethodId(5521375022094007015L).languageId(0x8baff8e6c33ed689L, 0x6b3888c1980244d8L).build2();

  private static final List<SMethod<?>> BH_METHODS = Arrays.<SMethod<?>>asList(populateTypeSignatures_id5q426iHK5S9, toString_id4nn3FPlZH$r, typeKey_idJmO2PmZtH5, isResolved_id4MvRlgZCbFz, tryResolve_id4MvRlgZCbFB);

  private static void ___init___(@NotNull SNode __thisNode__) {
  }

  /*package*/ static void populateTypeSignatures_id5q426iHK5S9(@NotNull SNode __thisNode__, SignatureCollector visitor) {
    {
      final SNode type = SLinkOperations.getTarget(__thisNode__, LINKS.nested$3t_j);
      if (SNodeOperations.isInstanceOf(type, CONCEPTS.IType$Ni)) {
        IType__BehaviorDescriptor.populateTypeSignatures_id5q426iHK5S9.invoke(type, visitor);
      }
    }
  }
  /*package*/ static String toString_id4nn3FPlZH$r(@NotNull SNode __thisNode__, boolean erased) {
    {
      final SNode type = SLinkOperations.getTarget(__thisNode__, LINKS.nested$3t_j);
      if (SNodeOperations.isInstanceOf(type, CONCEPTS.IType$Ni)) {
        IType__BehaviorDescriptor.toString_id4nn3FPlZH$r.invoke(type, ((boolean) erased));
      }
    }
    return "";
  }
  @NotNull
  /*package*/ static TypeKey typeKey_idJmO2PmZtH5(@NotNull SNode __thisNode__) {
    {
      final SNode type = SLinkOperations.getTarget(__thisNode__, LINKS.nested$3t_j);
      if (SNodeOperations.isInstanceOf(type, CONCEPTS.IType$Ni)) {
        return IType__BehaviorDescriptor.typeKey_idJmO2PmZtH5.invoke(type);
      }
    }
    return new UnmatchableType();
  }
  /*package*/ static boolean isResolved_id4MvRlgZCbFz(@NotNull SNode __thisNode__) {
    // This expression is the definition of unresolved business
    return false;
  }
  /*package*/ static SNode tryResolve_id4MvRlgZCbFB(@NotNull SNode __thisNode__) {
    if ((SLinkOperations.getTarget(__thisNode__, LINKS.nested$3t_j) == null)) {
      return null;
    }

    // This node will be replaced by its child when resolved
    if ((boolean) IResolvable__BehaviorDescriptor.isResolved_id4MvRlgZCbFz.invoke(SLinkOperations.getTarget(__thisNode__, LINKS.nested$3t_j))) {
      return SLinkOperations.getTarget(__thisNode__, LINKS.nested$3t_j);
    }

    return IResolvableReference__BehaviorDescriptor.tryResolveNamed_id4MvRlgZCbi_.invoke(SLinkOperations.getTarget(__thisNode__, LINKS.nested$3t_j), SPropertyOperations.getString(__thisNode__, PROPS.targetName$Bk$P));
  }

  /*package*/ UnresolvedParsedReference__BehaviorDescriptor() {
  }

  @Override
  protected void initNode(@NotNull SNode node, @NotNull SConstructor constructor, @Nullable Object[] parameters) {
    ___init___(node);
  }

  @Override
  protected <T> T invokeSpecial0(@NotNull SNode node, @NotNull SMethod<T> method, @Nullable Object[] parameters) {
    int methodIndex = BH_METHODS.indexOf(method);
    if (methodIndex < 0) {
      throw new BHMethodNotFoundException(this, method);
    }
    switch (methodIndex) {
      case 0:
        populateTypeSignatures_id5q426iHK5S9(node, (SignatureCollector) parameters[0]);
        return null;
      case 1:
        return (T) ((String) toString_id4nn3FPlZH$r(node, ((boolean) (Boolean) parameters[0])));
      case 2:
        return (T) ((TypeKey) typeKey_idJmO2PmZtH5(node));
      case 3:
        return (T) ((Boolean) isResolved_id4MvRlgZCbFz(node));
      case 4:
        return (T) ((SNode) tryResolve_id4MvRlgZCbFB(node));
      default:
        throw new BHMethodNotFoundException(this, method);
    }
  }

  @Override
  protected <T> T invokeSpecial0(@NotNull SAbstractConcept concept, @NotNull SMethod<T> method, @Nullable Object[] parameters) {
    int methodIndex = BH_METHODS.indexOf(method);
    if (methodIndex < 0) {
      throw new BHMethodNotFoundException(this, method);
    }
    switch (methodIndex) {
      default:
        throw new BHMethodNotFoundException(this, method);
    }
  }

  @NotNull
  @Override
  public List<SMethod<?>> getDeclaredMethods() {
    return BH_METHODS;
  }

  @NotNull
  @Override
  public SAbstractConcept getConcept() {
    return CONCEPT;
  }

  private static final class LINKS {
    /*package*/ static final SContainmentLink nested$3t_j = MetaAdapterFactory.getContainmentLink(0x6b3888c1980244d8L, 0x8baff8e6c33ed689L, 0x430acdda9dcb793eL, 0x430acdda9dcb79c6L, "nested");
  }

  private static final class CONCEPTS {
    /*package*/ static final SInterfaceConcept IType$Ni = MetaAdapterFactory.getInterfaceConcept(0x6b3888c1980244d8L, 0x8baff8e6c33ed689L, 0x28bef6d7551af441L, "jetbrains.mps.kotlin.structure.IType");
  }

  private static final class PROPS {
    /*package*/ static final SProperty targetName$Bk$P = MetaAdapterFactory.getProperty(0x6b3888c1980244d8L, 0x8baff8e6c33ed689L, 0x430acdda9dcb793eL, 0x430acdda9dcb9e4eL, "targetName");
  }
}
