package jetbrains.mps.lang.dataFlow.framework.analyzers;

/*Generated by MPS */

import jetbrains.mps.lang.dataFlow.framework.DataFlowAnalyzer;
import jetbrains.mps.lang.dataFlow.framework.VarSet;
import jetbrains.mps.lang.dataFlow.framework.Program;
import java.util.List;
import jetbrains.mps.lang.dataFlow.framework.ProgramState;
import jetbrains.mps.lang.dataFlow.framework.instructions.Instruction;
import jetbrains.mps.lang.dataFlow.framework.instructions.WriteInstruction;
import jetbrains.mps.lang.dataFlow.framework.AnalysisDirection;

public class InitializedVariablesAnalyzer implements DataFlowAnalyzer<VarSet> {
  public InitializedVariablesAnalyzer() {
  }
  @Override
  public VarSet initial(Program p) {
    return new VarSet(p, true);
  }
  @Override
  public VarSet merge(Program p, List<VarSet> input) {
    if (input.isEmpty()) {
      return initial(p);
    }
    VarSet result = new VarSet(p, true);
    for (VarSet anInput : input) {
      result.retainAll(anInput);
    }
    return result;
  }
  @Override
  public VarSet fun(VarSet input, ProgramState s) {
    Instruction instruction = s.getInstruction();
    VarSet result = input;
    if (s.isStart()) {
      result.clear();
    }
    if (instruction instanceof WriteInstruction) {
      WriteInstruction write = (WriteInstruction) instruction;
      result.add(write.getVariableIndex());
    }
    return result;
  }
  @Override
  public AnalysisDirection getDirection() {
    return AnalysisDirection.FORWARD;
  }
}
