package jetbrains.mps.baseLanguage.editor;

/*Generated by MPS */

import jetbrains.mps.editor.runtime.cells.AbstractCellAction;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.openapi.editor.EditorContext;
import jetbrains.mps.smodel.action.SNodeFactoryOperations;
import jetbrains.mps.editor.runtime.selection.SelectionUtil;
import jetbrains.mps.openapi.editor.cells.EditorCell;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;
import java.util.Objects;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import org.jetbrains.mps.openapi.model.SModel;
import java.util.List;
import jetbrains.mps.internal.collections.runtime.ISelector;
import org.jetbrains.mps.openapi.language.SConcept;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SConceptOperations;
import jetbrains.mps.internal.collections.runtime.IWhereFilter;
import jetbrains.mps.openapi.editor.cells.CellAction;
import jetbrains.mps.openapi.editor.cells.CellActionType;
import jetbrains.mps.nodeEditor.cellProviders.AbstractCellListHandler;
import org.jetbrains.mps.openapi.language.SContainmentLink;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;

public class ModifiersInsertHandler {

  /*package*/ static AbstractCellAction createAction_INSERT_BEFORE(final SNode node) {
    return new AbstractCellAction() {
      public String getDescriptionText() {
        return "disable enter behavior whenever it is the first member of the modifiers collection";
      }
      public void execute(EditorContext editorContext) {
        this.execute_internal(editorContext, node);
      }
      public void execute_internal(EditorContext editorContext, SNode node) {
        SNode newModifier = SNodeFactoryOperations.addNewChild(node, LINKS.modifiers$F5MM, null);
        SelectionUtil.selectNode(editorContext, newModifier);
      }
      @Override
      public boolean canExecute(EditorContext editorContext) {
        return this.canExecute_internal(editorContext, node);
      }
      public boolean canExecute_internal(EditorContext editorContext, SNode node) {
        EditorCell contextCell = editorContext.getSelectedCell();
        SNode contextNode = contextCell.getSNode();
        if (SNodeOperations.isInstanceOf(contextNode, CONCEPTS.Modifier$jW) && Objects.equals(ListSequence.fromList(SLinkOperations.getChildren(node, LINKS.modifiers$F5MM)).first(), contextNode)) {
          return false;
        }
        return true;
      }

    };
  }
  /*package*/ static AbstractCellAction createAction_INSERT(final SNode node) {
    return new AbstractCellAction() {
      public String getDescriptionText() {
        return "disable enter behavior unless it is the last member of the modifiers collection (or when there is a single element in the collection)";
      }
      public void execute(EditorContext editorContext) {
        this.execute_internal(editorContext, node);
      }
      public void execute_internal(EditorContext editorContext, SNode node) {
        SNode newModifier = SNodeFactoryOperations.addNewChild(node, LINKS.modifiers$F5MM, null);
        SelectionUtil.selectNode(editorContext, newModifier);
      }
      @Override
      public boolean canExecute(EditorContext editorContext) {
        return this.canExecute_internal(editorContext, node);
      }
      public boolean canExecute_internal(EditorContext editorContext, SNode node) {
        EditorCell contextCell = editorContext.getSelectedCell();
        SNode contextNode = contextCell.getSNode();
        if (SNodeOperations.isInstanceOf(contextNode, CONCEPTS.Modifier$jW)) {
          if (ListSequence.fromList(SLinkOperations.getChildren(node, LINKS.modifiers$F5MM)).count() <= 1) {
            // here I calculate whether there are some modifier concepts to insert at all. 
            // if yes then we allow to add a child into node.modifiers collection 
            SModel model = SNodeOperations.getModel(node);
            List<SNode> modifiers = SLinkOperations.getChildren(node, LINKS.modifiers$F5MM);
            return !(ListSequence.fromList(modifiers).select(new ISelector<SNode, SConcept>() {
              public SConcept select(SNode it) {
                return SNodeOperations.getConcept(it);
              }
            }).containsSequence(ListSequence.fromList(SConceptOperations.getAllSubConcepts2(CONCEPTS.Modifier$jW, model)).where(new IWhereFilter<SConcept>() {
              public boolean accept(SConcept it) {
                return !(it.isAbstract());
              }
            })));
          } else if (Objects.equals(ListSequence.fromList(SLinkOperations.getChildren(node, LINKS.modifiers$F5MM)).last(), contextNode)) {
            return false;
          }
        }
        return true;
      }

    };
  }

  public static void setCellActions(EditorCell editorCell, SNode node, EditorContext context) {
    CellAction originalDelete = editorCell.getAction(CellActionType.DELETE);
    CellAction originalBackspace = editorCell.getAction(CellActionType.BACKSPACE);

    // set actions that were actually defined 
    setDefinedCellActions(editorCell, node, context);

    // If we set a DELETE action but no BACKSPACE action, 
    // use the DELETE action for BACKSPACE as well. 
    CellAction delete = editorCell.getAction(CellActionType.DELETE);
    CellAction backspace = editorCell.getAction(CellActionType.BACKSPACE);
    if (delete != originalDelete && backspace == originalBackspace) {
      editorCell.setAction(CellActionType.BACKSPACE, delete);
    }
    if (delete != originalDelete) {
      editorCell.putUserObject(AbstractCellListHandler.ELEMENT_CELL_DELETE_SET, OB);
    }
    if (backspace != originalBackspace) {
      editorCell.putUserObject(AbstractCellListHandler.ELEMENT_CELL_BACKSPACE_SET, OB);
    }
  }

  private static final Object OB = new Object();

  public static void setDefinedCellActions(EditorCell editorCell, SNode node, EditorContext context) {
    // set cell actions from all imported action maps 

    // set cell actions defined directly in this action map 
    editorCell.setAction(CellActionType.INSERT_BEFORE, createAction_INSERT_BEFORE(node));
    editorCell.setAction(CellActionType.INSERT, createAction_INSERT(node));
  }

  public static void setDefinedCellActionsOfType(EditorCell editorCell, SNode node, EditorContext context, CellActionType actionType) {

    // set cell action(s) of the given type from imported action maps 

    // set cell action of the given type defined directly in this action map 
    if (Objects.equals(actionType, CellActionType.INSERT_BEFORE)) {
      editorCell.setAction(actionType, createAction_INSERT_BEFORE(node));
    }
    if (Objects.equals(actionType, CellActionType.INSERT)) {
      editorCell.setAction(actionType, createAction_INSERT(node));
    }
  }

  private static final class LINKS {
    /*package*/ static final SContainmentLink modifiers$F5MM = MetaAdapterFactory.getContainmentLink(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0x203eeb62af522fa5L, 0x203eeb62af522fb1L, "modifiers");
  }

  private static final class CONCEPTS {
    /*package*/ static final SConcept Modifier$jW = MetaAdapterFactory.getConcept(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0x21592d9e7375c5a6L, "jetbrains.mps.baseLanguage.structure.Modifier");
  }
}
