package jetbrains.mps.lang.typesystem.typesystem;

/*Generated by MPS */

import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;
import java.util.List;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import jetbrains.mps.smodel.SNodePointer;
import org.jetbrains.mps.openapi.language.SConcept;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import org.jetbrains.mps.openapi.language.SContainmentLink;
import org.jetbrains.mps.openapi.language.SReferenceLink;

public class RulesUtil {
  public static final Object MAY_BE_VARIABLE = new Object();
  public RulesUtil() {
  }
  public static boolean withinInferenceItem(SNode node) {
    if ((SNodeOperations.getNodeAncestor(node, CONCEPTS.InferenceRule$Ad, false, false) != null)) {
      return true;
    }
    if ((SNodeOperations.getNodeAncestor(node, CONCEPTS.InequationReplacementRule$4d, false, false) != null)) {
      return true;
    }
    List<SNode> annotations = SLinkOperations.getChildren(SNodeOperations.getNodeAncestor(node, CONCEPTS.BaseMethodDeclaration$RR, false, false), LINKS.annotation$4YGW);
    for (SNode annotation : annotations) {
      if (SLinkOperations.hasPointer(annotation, LINKS.annotation$lXdy, new SNodePointer("r:00000000-0000-4000-0000-011c895902b5(jetbrains.mps.lang.typesystem.dependencies)", "1196177069451"))) {
        return true;
      }
    }
    return false;
  }
  public static boolean withinTypeManagingItem(SNode node) {
    if ((SNodeOperations.getNodeAncestor(node, CONCEPTS.AbstractOverloadedOpsTypeRule$Sj, false, false) != null)) {
      return true;
    }
    if ((SNodeOperations.getNodeAncestor(node, CONCEPTS.SubtypingRule$86, false, false) != null)) {
      return true;
    }
    if ((SNodeOperations.getNodeAncestor(node, CONCEPTS.ComparisonRule$b9, false, false) != null)) {
      return true;
    }
    return false;
  }
  public static boolean withinCheckingItem(SNode node) {
    if ((SNodeOperations.getNodeAncestor(node, CONCEPTS.AbstractSubtypingRule$9o, true, false) != null)) {
      return true;
    }
    if ((SNodeOperations.getNodeAncestor(node, CONCEPTS.AbstractCheckingRule$l$, true, false) != null)) {
      return true;
    }
    List<SNode> annotations = SLinkOperations.getChildren(SNodeOperations.getNodeAncestor(node, CONCEPTS.BaseMethodDeclaration$RR, true, false), LINKS.annotation$4YGW);
    for (SNode annotation : annotations) {
      if (SLinkOperations.hasPointer(annotation, LINKS.annotation$lXdy, new SNodePointer("r:00000000-0000-4000-0000-011c895902b5(jetbrains.mps.lang.typesystem.dependencies)", "1196177069451")) || SLinkOperations.hasPointer(annotation, LINKS.annotation$lXdy, new SNodePointer("r:00000000-0000-4000-0000-011c895902b5(jetbrains.mps.lang.typesystem.dependencies)", "1223644778913"))) {
        return true;
      }
    }
    return false;
  }

  private static final class CONCEPTS {
    /*package*/ static final SConcept InferenceRule$Ad = MetaAdapterFactory.getConcept(0x7a5dda6291404668L, 0xab76d5ed1746f2b2L, 0x1117e2f5efaL, "jetbrains.mps.lang.typesystem.structure.InferenceRule");
    /*package*/ static final SConcept InequationReplacementRule$4d = MetaAdapterFactory.getConcept(0x7a5dda6291404668L, 0xab76d5ed1746f2b2L, 0x117c5668bf2L, "jetbrains.mps.lang.typesystem.structure.InequationReplacementRule");
    /*package*/ static final SConcept BaseMethodDeclaration$RR = MetaAdapterFactory.getConcept(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf8cc56b1fcL, "jetbrains.mps.baseLanguage.structure.BaseMethodDeclaration");
    /*package*/ static final SConcept AbstractOverloadedOpsTypeRule$Sj = MetaAdapterFactory.getConcept(0x7a5dda6291404668L, 0xab76d5ed1746f2b2L, 0x70bfdafbb2c9449bL, "jetbrains.mps.lang.typesystem.structure.AbstractOverloadedOpsTypeRule");
    /*package*/ static final SConcept SubtypingRule$86 = MetaAdapterFactory.getConcept(0x7a5dda6291404668L, 0xab76d5ed1746f2b2L, 0x1119c426ccaL, "jetbrains.mps.lang.typesystem.structure.SubtypingRule");
    /*package*/ static final SConcept ComparisonRule$b9 = MetaAdapterFactory.getConcept(0x7a5dda6291404668L, 0xab76d5ed1746f2b2L, 0x114caade477L, "jetbrains.mps.lang.typesystem.structure.ComparisonRule");
    /*package*/ static final SConcept AbstractSubtypingRule$9o = MetaAdapterFactory.getConcept(0x7a5dda6291404668L, 0xab76d5ed1746f2b2L, 0x1119c40dfb0L, "jetbrains.mps.lang.typesystem.structure.AbstractSubtypingRule");
    /*package*/ static final SConcept AbstractCheckingRule$l$ = MetaAdapterFactory.getConcept(0x7a5dda6291404668L, 0xab76d5ed1746f2b2L, 0x1164847e929L, "jetbrains.mps.lang.typesystem.structure.AbstractCheckingRule");
  }

  private static final class LINKS {
    /*package*/ static final SContainmentLink annotation$4YGW = MetaAdapterFactory.getContainmentLink(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0x114a6be947aL, 0x114a6beb0bdL, "annotation");
    /*package*/ static final SReferenceLink annotation$lXdy = MetaAdapterFactory.getReferenceLink(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0x114a6b4ccabL, 0x114a6b85d40L, "annotation");
  }
}
