package jetbrains.mps.samples.customizedDebugger.Bottomline.debug.plugin;

/*Generated by MPS */

import jetbrains.mps.plugins.part.ApplicationPluginPart;
import java.util.Set;
import jetbrains.mps.debug.api.BreakpointCreator;
import jetbrains.mps.internal.collections.runtime.SetSequence;
import java.util.HashSet;
import jetbrains.mps.debug.api.BreakpointCreatorsManager;
import jetbrains.mps.baseLanguage.closures.runtime._FunctionTypes;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SConceptOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;
import jetbrains.mps.debug.api.breakpoints.ILocationBreakpoint;
import com.intellij.openapi.project.Project;
import jetbrains.mps.debug.api.Debuggers;
import org.jetbrains.mps.openapi.language.SConcept;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;

public class DebugInfoProvider_AppPluginPart extends ApplicationPluginPart {
  private Set<BreakpointCreator> myCreators = SetSequence.fromSet(new HashSet<BreakpointCreator>());
  public DebugInfoProvider_AppPluginPart() {
  }
  @Override
  public void init() {
    BreakpointCreatorsManager manager = BreakpointCreatorsManager.getInstance();
    if (manager == null) {
      return;
    }

    {
      _FunctionTypes._return_P2_E0<? extends Boolean, ? super SAbstractConcept, ? super SNode> ccf = (SAbstractConcept concept, SNode debuggableNode) -> {
        if (SConceptOperations.isSubConceptOf(SNodeOperations.asSConcept(concept), CONCEPTS.OutputMessage$su)) {
          return true;
        }
        return false;

      };
      _FunctionTypes._return_P2_E1<? extends ILocationBreakpoint, ? super SNode, ? super Project, ? extends Exception> cf = (SNode debuggableNode, Project project) -> Debuggers.getInstance().getDebuggerByNameSafe("Java").createBreakpoint(debuggableNode, "JAVA_LINE_BREAKPOINT", project);
      BreakpointCreator creator = new BreakpointCreator(ccf, cf);
      SetSequence.fromSet(DebugInfoProvider_AppPluginPart.this.myCreators).addElement(creator);
      manager.addCreator(creator);
    }
  }
  @Override
  public void dispose() {
    BreakpointCreatorsManager manager = BreakpointCreatorsManager.getInstance();
    if (manager == null) {
      return;
    }
    for (BreakpointCreator creator : SetSequence.fromSet(DebugInfoProvider_AppPluginPart.this.myCreators)) {
      manager.removeCreator(creator);
    }
    SetSequence.fromSet(DebugInfoProvider_AppPluginPart.this.myCreators).clear();
  }

  private static final class CONCEPTS {
    /*package*/ static final SConcept OutputMessage$su = MetaAdapterFactory.getConcept(0x3f028972a2904cf2L, 0xa87e9b8f7e56076bL, 0x7df3f12f124a5e4L, "jetbrains.mps.samples.customizedDebugger.Bottomline.structure.OutputMessage");
  }
}
