package jetbrains.mps.baseLanguage.unitTest.platform;

/*Generated by MPS */

import java.util.Map;
import java.util.HashMap;

/**
 * A builder for {@link jetbrains.mps.baseLanguage.unitTest.platform.TestDescriptor }.
 * <p>
 * Only one of {@link jetbrains.mps.baseLanguage.unitTest.platform.TestDescriptorBuilder#newTest(String, SNodeTestSource) } or {@link jetbrains.mps.baseLanguage.unitTest.platform.TestDescriptorBuilder#newTestContainer(String, SNodeTestSource) } should be called.
 */
public class TestDescriptorBuilder {

  private final TestDescriptor myContainer;
  private String myName;
  private SNodeTestSource myTestSource;
  private TestDescriptor.Kind myKind;
  private Map<Object, Object> myProperties = new HashMap<>(4);

  public TestDescriptorBuilder(TestDescriptor container) {
    myContainer = container;
  }

  /**
   * Call this to create a new test. 
   */
  public TestDescriptorBuilder newTest(String name, SNodeTestSource testSource) {
    myName = name;
    myTestSource = testSource;
    myKind = TestDescriptor.Kind.TEST;
    return this;
  }

  /**
   * Call this to create a new test container.
   */
  public TestDescriptorBuilder newTestContainer(String name, SNodeTestSource testSource) {
    myName = name;
    myTestSource = testSource;
    myKind = TestDescriptor.Kind.TESTCONTAINER;
    return this;
  }

  public <T> TestDescriptorBuilder withProperty(TestProperties.Key<T> key, T value) {
    key.setValue(myProperties, value);
    return this;
  }

  /**
   * Invoke this method after having configured the builder to commit the test/test container to its own container.
   */
  public TestDescriptor add() {
    TestDescriptor descriptor = new TestDescriptor(myName, myTestSource, myKind, myProperties);
    myContainer.addTest(descriptor);
    return descriptor;
  }

}
